### ISSUE TITLE
Documentation needs lots of love, pleaaase. 🙏 

### ISSUE THREAD

**Issue by govindrai** [googleapis/nodejs-logging#1003]
**Is your feature request related to a problem? Please describe.**
I'm pretty frustrated by _all_ the node.js client libraries' documentation. 

Let's take an example with the Node Logging Client. Let's say I want to create a sink. Searching "createSink" returns 5 different ways for me to create a sink: 
![image](https://user-images.githubusercontent.com/13859249/111334476-d4b33a80-8630-11eb-806b-ac2b482042fc.png)
![image](https://user-images.githubusercontent.com/13859249/111334541-ded53900-8630-11eb-8b3f-24a45e9ebdc3.png)
_This one has all methods doubly listed which may be a separate bug_
![image](https://user-images.githubusercontent.com/13859249/111334793-193ed600-8631-11eb-9f13-de135ab3a944.png)
![image](https://user-images.githubusercontent.com/13859249/111334850-252a9800-8631-11eb-9b16-720e2847aa8e.png)

Oh and you can also use Sink#create as well.
![image](https://user-images.githubusercontent.com/13859249/111334573-e85ea100-8630-11eb-8213-ecff4b4c42b6.png)

Can we cut down on the noise? There's nothing particularly complex that an end user is trying to do with these sdks. Just basic crud operations on resources. However, the docs are littered which 100s of methods to various classes that for the most part are not used directly (i.e. another method is calling them). 

The left hand side bar includes so many links to so many different classes, that to find any relevant apis, one has either scroll forever or read through a ton of classes they may never use. There's 122 classes listed in the sidebar.. For example when loading the docs for Logging, the first three class are:
![image](https://user-images.githubusercontent.com/13859249/111330226-fca09f00-862c-11eb-9872-ccde982ddc00.png)

You're most likely never going to interface with any of those classes directly (i.e there's another API method that instantiating and using those classes). Maybe it makes sense to link directly in the docs of those higher level API methods where they're relevant and not in the main catalogue. Or to list these other classes at the very bottom and have them be in a drawer that can be collapsed if needed. Or simply hide the internals.

Secondly there are so many classes (i.e. LoggingServiceV2Client, ConfigServiceV2Client, MetricServiceV2Client) and there's overlap in between them. What are these for? The examples don't use them, when are you supposed one over the other? Many of these classes don't have any examples of their usage. 

In my experience (I have been using the about 10 of node SDKs for over 2 years), almost all of the docs seem to be noise for the intended end user, and reading the docs is pretty exhausting. I either end up having to resort to the internet, using the gcloud sdk directly, or try to find my usecase buried in examples (which I believe are a byproduct of how noisy the docs are, and have lead documentation authors to have to maintain and update examples). If you're lucky enough, you can avoid looking at the docs altogether, which leads me to question the utility of these behemoth docs in the first place). Those examples are just another thing which need to be kept updated versus just having the examples documented at the source of the api.

I would suggest looking at AWS' node.js docs for inspiration (see logs for [CloudWatchLogs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudWatchLogs.html)). For any service offering, they have all the api methods on one _single_  page, that lists all the actions you can take against that service. Almost always, you can do a simple find and search for exactly what you're looking for--you'd either you'd hit the name of the method you need or you'd hit some relevant term in the docs pertaining to the method. In google node client library docs, functionality is segmented across different links and there is no global search to search across them, so you have to scroll and hope you select the link you're looking for, otherwise go back and try to find another link. 

Now maybe I just don't understand how to read this docs, and if that's the case, then please enlighten me 😄. Maybe there could be some guidance around how to use the docs, but it seems to me that the docs needs some reorganization, some focus. I would super appreciate someone looking at this. The documentation needs a _lot_ of love. I'd be happy to help give more detailed feedback or talk with someone who manages documentation. 

PS. I write this with sincerity and respect, and hopefully the tone is not coming across as rude.

**Comment by stephenplusplus** [comment]
Thank you for taking the time to write this up, and ultimately help us and others. I think you're right-- it's not clear how to do a simple operation, when there's so many options presenting themselves, most using names that never needed to escape the internals of our library.

I think a simple first step would be separating the two types of docs; our API from the full (generated) API. I'm not sure how our docs templates are constructed, but it seems doable. @nicoleczhu do you know where we could start?

**Comment by nicoleczhu** [comment]
These reference docs are indeed verbose. The Nodejs-logging library intentionally offers helpful wrappers, defaults and sugar functions at several layers of abstraction on top of the raw logging API. The docs are autogenerated to feature all of these layers. It's too much info for most users, since 80%+ probably just use the top level abstraction. But extreme case users who might want to alter things like gaxOptions do need the reference docs.

I'm chatting with the Node team next week to see how we can better format/organize the reference docs for a better UX. The information scope likely won't be reduced, but they should definitely be better organized!

Separately, [logging samples page](https://cloud.google.com/logging/docs/samples) highlights all top level library features and is more opinionated about how could be used. 

In the meantime, let me know what you

**Comment by nicoleczhu** [comment]
I haven't heard back from internal folks on this, though there is an early stage project moving away from our current doc autogenerator. 

For now, I plan to at least update the [NPM docs](https://www.npmjs.com/package/@google-cloud/logging), and make sure it has all the samples featured [here](https://cloud.google.com/logging/docs/samples).

**Comment by keenan-devrel** [comment]
We will try to address this by the end of Q3 2021.

**Comment by keenan-devrel** [comment]
It is looking more like Q4 2021 before this can be addressed.

**Comment by losalex** [comment]
Hi @govindrai,
Thanks a lot for opened issue and sorry it took time to get to it. I was trying to repro the problems you mentioned in this ticket and apparently I cannot repro same behavior exactly. For example when I try to search for createsink, I get suggestions dropdown list which in addition to regular suggested searches provides results scoped by specific language like in image below (e.g. suggested pages):
![image](https://user-images.githubusercontent.com/90795544/144504383-3f9f6882-dede-412f-a841-d05353b8a44f.png)

When I choose suggested search from drop down list, I am getting search results like in picture below:

![image](https://user-images.githubusercontent.com/90795544/144505561-4b2b090b-07c1-453c-a5cf-e52a5fc04328.png)

If I choose suggested page, I am navigating to specific page. I wonder if you can still repro specific issue you had and it would be great if you can share exact steps led to a problem.
Thank you very much!

**Comment by intellix** [comment]
It would also be nice to know the permissions required by the service account. All I get in my logs is:
> Error: 7 PERMISSION_DENIED: The caller does not have permission
    at Object.callErrorFromStatus (/app/node_modules/@google-cloud/logging/node_modules/@grpc/grpc-js/build/src/call.js:31:26)

Guessing there's a list of permissions required by this module to do whta it needs

**Comment by govindrai** [comment]
@losalex I'm not sure where you are doing your searches, but you can 100% still repro the problem if you go to the Node.js Logging Client docs. Here's your link: https://googleapis.dev/nodejs/logging/latest/index.html 

Everything in my original post still stands.

**Comment by losalex** [comment]
Thank you @govindrai for providing a link - I assigned this issue on @fhinkel

**Comment by fhinkel** [comment]
Thanks for the detailed write up. We moved the reference docs to 
https://cloud.google.com/nodejs/docs/reference/logging/latest

The navigation got tidied up quite a bit. But as reference docs go, they cover everything and are thus verbose. For more of a tutorial style document, I'd look at https://cloud.google.com/logging/docs/setup/nodejs. 

cc @simonz130 if their team wants to prioritize more tutorial style docs.
