### ISSUE TITLE
feat: let users write structured json logs to stdout

### ISSUE THREAD

**Issue by nicoleczhu** [googleapis/nodejs-logging#1036]
To support offline development && agents teams using this lib (e.g. Cloud Functions, and Cloud Run) we should let users write structured log entries (in json format) to stdout. This will be subsequently picked up by agents running in specific environments. This also allows nice debugging ux during development.

LogEntry format written to API:  JSON.stringify([logEntry](https://cloud.google.com/logging/docs/structured-logging))
Current workaround/painpoint we're hoping to solve: https://cloud.google.com/functions/docs/monitoring/logging#writing_structured_logs 

Fields currently lifted by serverless agents, syntax specific: 
```
message
severity
log
logging.googleapis.com/trace
logging.googleapis.com/trace_sampled
logging.googleapis.com/spanId
logging.googleapis.com/operation
httpRequest
timestamp
timestampSeconds
timestampNanos
time
logging.googleapis.com/sourceLocation
logging.googleapis.com/insertId
logging.googleapis.com/labels
```

Spec: 
- users' default transport is writing to loggingService api
- users can create Log with opt transport set to stdout (stderr too?)
- users can change transport to stdout (and back to api)
- users get all the same decorated properties autodetected

Will discard previous impl in branch: `hackathon`

**Comment by jordanebelanger** [comment]
+1 to this, I am on cloud run and simply want to be able to log the entries to stdout rather than call the API
