### ISSUE TITLE
Release v1.2.0 to npm

### ISSUE THREAD

**Issue by FalconerTC** [googleapis/nodejs-logging#104]
It looks like v1.2.0 has been out for over a week but @google-cloud/logging hasn't been updated. Is this intentional?

**Comment by stephenplusplus** [comment]
Thanks for catching that! Our releases are done automatically through CI, and it looks like one of our tests preceding the release step flaked out. That blocked the release, but I've just triggered a re-build and confirmed 1.2.0 was published to npm.
