### ISSUE TITLE
Object implementing toString not logged as Object

### ISSUE THREAD

**Issue by g3offrey** [googleapis/nodejs-logging#1076]
#### Environment details

  - OS: MacOS / Linux (but I think this is not relevant)
  - Node.js version: 10 (but I think this is not relevant)
  - npm version: 6 (but I think this is not relevant)
  - `@google-cloud/logging` version: 9.2.3

#### Steps to reproduce

  1. Try to log with an object as payload. This object MUST implement a custom `toString` method.
  2. Checkout the result on GCP console / logging.

Hello 👋 
First of all, thank you for developing this library permitting us to integrate easily with logging on GCP. ❤️ 

Today I encountered an issue trying to log a custom object coming from a third party library.
Indeed this object implemented its own `toString` method and was not recognized as an object by nodejs-logging.
I think this is the line of code responsible for this behavior. 
https://github.com/googleapis/nodejs-logging/blob/1cce0d3c79c4b33c0e4920b6be90a45701e7c7df/src/common.ts#L132

The solution would be to reuse the old way to check value is an object (`is.object`).
Or use a similar way as `isobject` library (https://github.com/jonschlinkert/isobject), even if this seems discouraged as the comment says.
```js
  return val != null && typeof val === 'object' && Array.isArray(val) === false;
```

If this behavior is intended, feel free to close my issue, as a possible workaround is to clone the object I want to log, into another one that does not have the `toString` override. 
However I think maybe I'm not be the only one experiencing this issue.
 
For information the library responsible for writing its own custom `toString` is AVSC.(https://github.com/mtth/avsc/blob/e16dbf642c5999c7e5ab09c536d7310f6b7a1fde/lib/types.js#L664) 

If I'm not clear enough, feel free to reach me. I'll be glad to write a PR to fix this issue if this could ease you (once we agree on a solution).

Thank you ! 😄

**Comment by nicoleczhu** [comment]
Ahh interesting, this is a important edge case we should handle. 

What does your custom obj look like? What is the str when you do `.toString` to it?

The small challenge here is that we don't want to use 3rd party libraries for type detection, so we'd have to handle it with some custom code.

**Comment by g3offrey** [comment]
Hello @nicoleczhu 

Thank you for your fast answer 👌 

My custom object is an instance of a class which looks line this at the end, when console.logged (an object containing nested objects) : 
```js 
{
  order: {
    customer: {
      address: {
        city: "Paris",
        ...
      }
    }
  }
}
```

The `toString` function only do a `JSON.stringify` on it.

Yeah I totally understand the will of not using 3rd party code to check types, and I think this is the best way to achieve this.

The proposed fix, should be fine in my opinion. My object has indeed a `typeof === "object"`.

Thank you for proposing a solution this fast 😄

**Comment by nicoleczhu** [comment]
np, happy to help. @g3offrey , so i ended up doing `Object.prototype.toString.call(value) === '[object Object]'` instead, which is valid for your use case. I tested with: 

var testObj = {
  foo: "bar",
  toString: () => {
   return "lalala"
  }
}

if (Object.prototype.toString.call(value) === '[object Object]') =====> evaluates to true

let me know if it doesn't work though - you never know. Also this release might take a few days. We dont release on Fridays. Thanks for reporting and have a good weekend

**Comment by g3offrey** [comment]
I tested with `Object.prototype.toString.call(value) === '[object Object]'` and it is working completely fine.
This is a clever solution, good job 💯 

Sure, we have the same rules in my company to keep a weekend worry free 😂

Thank your for fixing this fast. I wish you a nice weekend ! 👋
