### ISSUE TITLE
node-pre-gyp is wrong version: expected "^0.10.0", got "0.6.39"

### ISSUE THREAD

**Issue by zamiang** [googleapis/nodejs-logging#108]
Have been unable to install this node module without errors. I always get the error `error "@google-cloud/logging#@google-cloud/common-grpc#grpc#node-pre-gyp" is wrong version: expected "^0.10.0", got "0.6.39"`

#### Environment details

  - OS: OSX / Ubuntu via circleci
  - Node.js version: 8.11
  - npm version:
```
    "@google-cloud/error-reporting": "0.4.0",
    "@google-cloud/logging": "1.2.0",
    "@google-cloud/storage": "1.6.0",
    "@google-cloud/trace-agent": "2.8.1",
```

#### Steps to reproduce

  1. install the node module using yarn 1.6.0
  2. `$ yarn check --verify-tree`

**Comment by stephenplusplus** [comment]
@alexander-fenster any ideas about this?

**Comment by alexander-fenster** [comment]
Could not repro:

```sh
yarn add @google-cloud/logging
yarn check --verify-tree
```
worked for me without any errors:
```
$ yarn check --verify-tree
yarn check v1.6.0
warning package.json: No license field
success Folder in sync.
Done in 0.67s.
```

Here are the versions I got:
```
$ grep '"version":' node_modules/{@google-cloud/logging,@google-cloud/common-grpc,grpc,node-pre-gyp}/package.json
node_modules/@google-cloud/logging/package.json:  "version": "1.2.0",
node_modules/@google-cloud/common-grpc/package.json:  "version": "0.6.1",
node_modules/grpc/package.json:  "version": "1.11.3",
node_modules/node-pre-gyp/package.json:  "version": "0.10.0",
$ node --version
v8.9.1
$ yarn --version
1.6.0
```

Can you paste the complete output of `yarn add @google-cloud/logging`?

**Comment by zamiang** [comment]
Ah yea apologies, I tried to include in the description but yea - it is an issue with adding ` @google-cloud/logging` to a project that already has `"@google-cloud/error-reporting": "0.4.0",  "@google-cloud/storage": "1.6.0",  "@google-cloud/trace-agent": "2.8.1",`

**Comment by alexander-fenster** [comment]
@zamiang Thanks! Still cannot repro :)

```
$ yarn check --verify-tree
yarn check v1.6.0
warning package.json: No license field
success Folder in sync.
Done in 0.63s.
fenster@fenster ws screen:/tmp/yarn-test$ cat package.json 
{
  "dependencies": {
    "@google-cloud/error-reporting": "^0.4.0",
    "@google-cloud/logging": "^1.2.0",
    "@google-cloud/storage": "^1.6.0",
    "@google-cloud/trace-agent": "^2.8.1"
  }
}
```

Can I ask you to do it in the clean folder?

```sh
mkdir clean-folder && cd clean-folder && yarn add @google-cloud/error-reporting @google-cloud/storage @google-cloud/trace-agent @google-cloud/logging && yarn check --verify-tree
```

**Comment by alexander-fenster** [comment]
One more point here is that of the four modules you mentioned, only `@google-cloud/logging` uses gRPC, the other three don't so they should not affect the gRPC dependency tree in any way.

**Comment by stephenplusplus** [comment]
I tried and failed to reproduce as well. I'm going to close, but feel free to provide more information that could prove we have an issue.
