### ISSUE TITLE
uuid should be a production dependency?

### ISSUE THREAD

**Issue by aeaton-overleaf** [googleapis/nodejs-logging#1115]
The `uuid` dependency is imported in `utils/context`, but is only mentioned in `devDependencies`:

https://github.com/googleapis/nodejs-logging/blob/f4e892ed1342f3aacb8056212d75792959ab43b5/src/utils/context.ts#L31

https://github.com/googleapis/nodejs-logging/blob/f4e892ed1342f3aacb8056212d75792959ab43b5/package.json#L92

It feels like `uuid` should be a production dependency?

**Comment by simonz130** [comment]
This is fixed in #1119
