### ISSUE TITLE
Unclear how LogSync gets HTTP headers

### ISSUE THREAD

**Issue by cakoose** [googleapis/nodejs-logging#1116]
I'm using Cloud Run and noticed the `LogSync` section here: https://github.com/googleapis/nodejs-logging#writing-to-stdout

> It extracts additional log properties like trace context from HTTP headers and ...

How does it extract stuff from HTTP headers?  Do I have to call a function and pass it the HTTP request object?

**Comment by minherz** [comment]
Maybe it can be done via installing [middleware](https://github.com/googleapis/nodejs-logging/blob/main/src/middleware/express/make-middleware.ts) so it intercepts requests and populates proper fields.

**Comment by losalex** [comment]
LogEnry class has [httpRequest](https://github.com/googleapis/nodejs-logging/blob/15849160116a814ab71113138cb211c2e0c2d4b4/src/entry.ts#L53) property which could be assigned with [HttpRequest](https://github.com/googleapis/nodejs-logging/blob/15849160116a814ab71113138cb211c2e0c2d4b4/src/entry.ts#L43).
Please refer to tests on how it can be used - for example the test for [trace and span](https://github.com/googleapis/nodejs-logging/blob/b361673772a632bcee0e5a2d089cc42d78e64e4f/test/entry.ts#L271) detection
