### ISSUE TITLE
Making googleapis/nodejs-logging/src/utils/metadata.ts available to the public

### ISSUE THREAD

**Issue by LuWang1983** [googleapis/nodejs-logging#1125]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Hi,
I'm wondering if the metadata module will ever be made public. Currently only detectServiceContext() is exported on the index page and the rest of the functions in that module are private. 
The reason I'm asking is because we are using winston for our logging system and logging-winston to establish transports to Google Logging. Without manually configuring the cloud resource in the transport, the resource will default to global if it's on a resource that doesn't automatically fill in for the log entries. 

 **Describe the solution you'd like**
Make metadata module available to the public. 
 **Describe alternatives you've considered**
We copy/pasted the code and monkey patched it with license included. 
 **Additional context**

**Comment by minherz** [comment]
hi,
we are working on introducing implicit [structured logging](https://cloud.google.com/logging/docs/structured-logging) into all our logging libraries including [nodejs-logging-winston](https://github.com/googleapis/nodejs-logging-winston). the goal is to have structured log entries sent to Cloud Logging without a need for any changes in application code. The change will include automatic discovery of the environment where the application running and populating [log entry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) fields including metadata accordingly.
Until then you can explicitly populate [MonitoredResource](https://github.com/googleapis/nodejs-logging-winston/blob/master/src/index.ts#L70) with a [proper value](https://cloud.google.com/monitoring/api/resources).

Please, let us know if this info address your question.

**Comment by LuWang1983** [comment]
Thank you! We are currently using the metadata module to auto detect but this is really helpful, thank you for the quick response!
