### ISSUE TITLE
Sync log name not queryable using `logName=`

### ISSUE THREAD

**Issue by averikitsch** [googleapis/nodejs-logging#1128]
#### Environment details

  - OS: Container (base node:12-slim)
  - Node.js version: 12
  - npm version: 7.18.1
  - `@google-cloud/logging` version: 9.5.4

#### Steps to reproduce

  1. Create service w/ code:
 ```
  const {Logging} = require('@google-cloud/logging');
  const logging = new Logging();
  await logging.setProjectId()
  await logging.setDetectedResource()

  const msg = "my test sync message";
  const metadata = {
    severity: 'ERROR',
  };

  const log = logging.logSync("test-sync-name");
  const entry = log.entry(metadata, msg);
  log.write(entry);
```
2. Deploy to Cloud Run:
```
gcloud beta run deploy logging-test --source .
```

3. Try querying in Cloud Logging console:
```
resource.type="cloud_run_revision"
logName="projects/PROJECT/logs/test-sync-name"
```
Above does not work compared to:
```
resource.type="cloud_run_revision"
jsonPayload.logName="projects/PROJECT/logs/test-sync-name"
```
I would expect to query the log name the same as other logs and not have to search the JSON payload

**Comment by losalex** [comment]
It seems no repro anymore - closing it
