### ISSUE TITLE
HTTP logging and log-correlation needs better documentation

### ISSUE THREAD

**Issue by averikitsch** [googleapis/nodejs-logging#1129]
**Is your feature request related to a problem? Please describe.**
The [HTTP request sample](https://github.com/googleapis/nodejs-logging/blob/master/samples/http-request.js) shows constructing your own metadata object. This is not a great developer experience since many logging libraries can automatically do that for you. However, found via the [library tests](​​https://github.com/googleapis/nodejs-logging/blob/ad1067bf5820c41b3a80546feb259c76607fa338/test/entry.ts#L294), you can pass in the `req` object: `entry.metadata.httpRequest = req;`. 

 **Describe the solution you'd like**
This solution should be added or mentioned in the sample. The READMe or docs should also mention that this solution also does log-request correlation automatically for you.

**Comment by averikitsch** [comment]
Hi @minherz, I dug into this issue and the library does support the conversion of a HTTP request object to the HTTP Request proto https://github.com/googleapis/nodejs-logging/blob/15849160116a814ab71113138cb211c2e0c2d4b4/src/entry.ts#L226-L229. This functionality makes this library more useful since it will automatically parse the trace header for you.

**Comment by minherz** [comment]
Thank you, @averikitsch. You are right. I am not sure whether it can be used in the [referenced example](https://github.com/googleapis/nodejs-logging/blob/master/samples/http-request.js). The [documentation](https://cloud.google.com/logging/docs/reference/libraries#logging_write_log_entry_advanced-nodejs) (and also [here](https://cloud.google.com/logging/docs/samples/logging-write-log-entry-advanced#logging_write_log_entry_advanced-nodejs)) shows that samples are aligned to demonstrate how the http request metadata can be populated.

I agree that documenting the feature that implicitly supports the type conversion will be useful for developers. We will add a paragraph with a sample to the repository README.
