### ISSUE TITLE
Async logs can't detect Cloud Run resource type

### ISSUE THREAD

**Issue by averikitsch** [googleapis/nodejs-logging#1130]
#### Environment details

  - OS: Container node:12-slim
  - Node.js version: 12
  - npm version: 7.18.1
  - `@google-cloud/logging` version: 9.5.4

#### Steps to reproduce

  1. Create Service with code:
```
  const {Logging} = require('@google-cloud/logging');
  const logging = new Logging();

  const msg = "my test message";
  const metadata = {
    severity: 'ERROR',
  };

  const log = logging.log("test-log-name");
  const entry = log.entry(metadata, msg);
  await log.write(entry);
```
  2. Deploy to Cloud Run
  3. View Logs
The resource type is set to global, so you are unable to use query: `resource.type="cloud_run_revision"`

```
{
  "insertId": "..........4Aj9lcgid2SNy8GYc3.OUb",
  "jsonPayload": {
    "arbitrary": "new field",
    "test": "my message"
  },
  "httpRequest": {
...
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "PROJECT"
    }
  },
...
}
```

**Comment by JCMais** [comment]
I think this was fixed by https://github.com/googleapis/nodejs-logging/pull/1145

**Comment by losalex** [comment]
Yep, seems it was fixed already
