### ISSUE TITLE
Question on LogEntry use in TypeScript

### ISSUE THREAD

**Issue by jason-formby-SM** [googleapis/nodejs-logging#1135]
Hello,

The samples/logs.js shows accessing the LogEntry payload like:
```
const metadata = entry.metadata;
console.log(`${metadata.timestamp}:`, metadata[metadata.payload]);
```

This doesn't work in TypeScript since `payload` isn't part of the `ILogEntry` interface.

My current work around is to do:
```
import { google } from '@google-cloud/logging/build/protos/protos'
const metadata = entry.metadata as google.logging.v2.LogEntry;
if (metadata.payload ) {
    console.log(`${metadata.timestamp}:`, entry.data, metadata[metadata.payload]);
} else {
    ...
}

```

Is the correct way to use LogEntry in TypeScript?

Thanks,
Jason

**Comment by minherz** [comment]
hi,
i am not sure about the path in npm but we provide an autogenerated code in [proto.js](https://raw.githubusercontent.com/googleapis/nodejs-logging/master/protos/protos.js). The file includes all protos from `https://github.com/googleapis/nodejs-logging/tree/master/protos/google` and you might want to optimize its size be excluding some or generated relevant code from .proto by yourself.
The generated code provides you with a class `LogEntry` with properties `jsonPayload` and `textPayload`.
