### ISSUE TITLE
add environment test as presubmit check

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/nodejs-logging#1138]
We should have the environment tests run before each PR, like in the Python library

**Comment by losalex** [comment]
We do have tests which could be run from terminal, e.g. "npm run test" - can you please elaborate what you mean here?

**Comment by daniel-sanche** [comment]
I was referring to having the environment tests run on each PR, but it looks like we have that in place already:
![image](https://user-images.githubusercontent.com/3914119/146835376-fe7503b8-65d0-49d7-bda1-542b2537984d.png)

This must be out of date
