### ISSUE TITLE
This module uses version 1.0.0 of eventid that still uses uuid 3.4.0

### ISSUE THREAD

**Issue by markrity** [googleapis/nodejs-logging#1143]
**Is your feature request related to a problem? Please describe.**
uuid module is still 3.4.0 at release version 
 **Describe the solution you'd like**
Described here: https://github.com/google/eventid-js/issues/156
This module uses version 1.0.0 of eventid that still uses uuid 3.4.0 at release version 1.0.0 , even though it was upgraded to 8 and upper at `main` branch...
So you get this error when installing logging module:
```
warning @google-cloud/logging > eventid > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

```

Would be great if it was updated.

 **Describe alternatives you've considered**
Not using outdated packages
 **Additional context**
Thank you guys.

**Comment by losalex** [comment]
I see that eventid was upgraded to version 2.0.0 [here](https://github.com/google/eventid-js/issues/156) and also this repository was updated with new eventid reference [here](https://github.com/googleapis/nodejs-logging/commit/2c4b4c1bca7859cd15fd611653d8b35983fe5915#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
