### ISSUE TITLE
System tests not working?

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging#115]
With a fresh npm install of current `master` against Node 10, I am seeing the system tests fail with an out of memory. Is this just me, or have we seen this before?

```sh
~/src/veneer/nodejs-logging common-0.18.9* 3m 42s
❯ npm run system-test

> @google-cloud/logging@1.2.0 system-test /Users/ofrobots/src/veneer/nodejs-logging
> repo-tools test run --cmd mocha -- system-test/*.js --timeout 600000

run: Executing tests in: /Users/ofrobots/src/veneer/nodejs-logging
run: Running: mocha system-test/logging.js --timeout 600000


  Logging
    sinks
      ✓ should create a sink with a Bucket destination (1903ms)
      ✓ should create a sink with a Dataset destination (1067ms)
      ✓ should create a sink with a Topic destination (1627ms)
      metadata
        ✓ should set metadata (191ms)
        ✓ should set a filter (177ms)
      listing sinks
        ✓ should list sinks (102ms)
        ✓ should list sinks as a stream (153ms)
        ✓ should get metadata (248ms)
    logs
      ✓ should list log entries (1251ms)
      ✓ should list log entries as a stream (388ms)
      ✓ should write a single entry to a log (307ms)
      ✓ should write multiple entries to a log (10569ms)
      ✓ should preserve order of entries (41520ms)
      ✓ should preserve order for sequential write calls (40308ms)
      ✓ should write an entry with primitive values (10643ms)
      ✓ should write a log with metadata (10643ms)
      ✓ should set the default resource (10552ms)
      ✓ should write a log with camelcase resource label keys (175ms)
      ✓ should write to a log with alert helper (173ms)
      ✓ should write to a log with critical helper (144ms)
      ✓ should write to a log with debug helper (234ms)
      ✓ should write to a log with emergency helper (599ms)
      ✓ should write to a log with error helper (180ms)
      ✓ should write to a log with info helper (149ms)
      ✓ should write to a log with notice helper (172ms)
      ✓ should write to a log with warning helper (200ms)
      log-specific entries
        ✓ should list log entries (290ms)
        ✓ should list log entries as a stream (611ms)

<--- Last few GCs --->

[51948:0x102802400]   382188 ms: Mark-sweep 1397.0 (1447.8) -> 1397.0 (1447.8) MB, 5258.5 / 0.0 ms  allocation failure GC in old space requested
[51948:0x102802400]   387378 ms: Mark-sweep 1397.0 (1447.8) -> 1397.0 (1431.8) MB, 5189.2 / 0.0 ms  last resort GC in old space requested
[51948:0x102802400]   392697 ms: Mark-sweep 1397.0 (1431.8) -> 1397.0 (1431.8) MB, 5318.8 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x335943b0427d]
Security context: 0x6925a3a06a9 <JSObject>
    1: ServiceObject [/Users/ofrobots/src/veneer/nodejs-logging/node_modules/@google-cloud/common/src/service-object.js:~63] [pc=0x335943e684ca](this=0x69275bd7c71 <File map = 0x692fcdc2df1>,config=0x69275bd7cf1 <Object map = 0x692fcdc2c11>)
    2: /* anonymous */ [/Users/ofrobots/src/veneer/nodejs-logging/node_modules/@google-cloud/storage/src/bucket.js:~105...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/ofrobots/.nvm/versions/node/v10.0.0/bin/node]
 2: node::FatalTryCatch::~FatalTryCatch() [/Users/ofrobots/.nvm/versions/node/v10.0.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/ofrobots/.nvm/versions/node/v10.0.0/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/ofrobots/.nvm/versions/node/v10.0.0/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/ofrobots/.nvm/versions/node/v10.0.0/bin/node]
 6: 0x335943b0427d
run: Oh no! Test failed after 395s.
```

**Comment by alexander-fenster** [comment]
Works for me on rodete on both node8 and node10. Also, works in Circle without any problems.

**Comment by ofrobots** [comment]
I observed the failure on a mac. Can someone else give it a shot on a mac too? I can dig in deeper when I get cycles.

**Comment by alexander-fenster** [comment]
Works for me on Mac as well.

**Comment by ofrobots** [comment]
I can reliably reproduce this on my mac. It seems like a closure memory leak from `@google-cloud/storage/src/acl.js`. Still debugging.

**Comment by ofrobots** [comment]
So, in my project I had some storage buckets named `gcloud-logging-test${suffix}` created by logging systems tests – but I am guessing from a long time ago. Collectively these buckets had 230k files in them. I have no idea how.

The system tests try to delete all storage buckets matching the `gcloud-logging-test` prefix in the `afterAll` hook. We were running out of memory trying to do that.

The question this raises:
* As a user if I really have large storage bucket with lots of files, is it possible for me to delete those files without running out of memory? I can open this as an issue in the storage repo.
* How did I get such large storage buckets from the logging system tests in the first place?

/cc @stephenplusplus

**Comment by stephenplusplus** [comment]
> As a user if I really have large storage bucket with lots of files, is it possible for me to delete those files without running out of memory? I can open this as an issue in the storage repo.

The way the system tests deletes the buckets could have been optimized to handle large amounts. We do a "get all, then delete all", while a pagination method would have worked better, had we planned on so many objects existing.

> How did I get such large storage buckets from the logging system tests in the first place?

I'm not exactly sure. If anyone has ever had stale buckets leftover from all the years of testing (almost 4 now!), it's been me, but my [storage browser](https://console.cloud.google.com/storage/browser) is clean. Could it be a case where you had an intense debugging round sometime in the past, where you left off the `afterAll` hook?

**Comment by ofrobots** [comment]
I am still puzzled about how I got 230k files in the test buckets created by the system tests. I do not remember any intense debugging session that might have motivated me to create all those files.

>The way the system tests deletes the buckets could have been optimized to handle large amounts.

I'll leave it up to you whether this is worthwhile.

**Comment by JustinBeckwith** [comment]
Everything seems to be moving smoothly, so I'm going to go ahead and close this out for now.  Please do let me know if you have any concerns!
