### ISSUE TITLE
This package must declare `@types/long` as a dependency

### ISSUE THREAD

**Issue by alamothe** [googleapis/nodejs-logging#1184]
This package must declare `@types/long` as a dependency since it's importing `"long"` in its typings.

Please check: https://yarnpkg.com/getting-started/migration#fix-dependencies-with-packageextensions

**Comment by minherz** [comment]
hi @alamothe ,
can you be more specific in your request? I do not find the use of long type anywhere in the code.

**Comment by alamothe** [comment]
@minherz Thank you for your reply!

It exists in the build artifact under `build/protos/protos.d.ts`:
```tsx
import * as Long from "long";
import {protobuf as $protobuf} from "google-gax";
/** Namespace google. */
export namespace google {

    /** Namespace protobuf. */
    namespace protobuf {

        /** Properties of a Duration. */
        interface IDuration {

            /** Duration seconds */
            seconds?: (number|Long|string|null);
```
The way I understand it is, TypeScript will complain unless `@types/long` is included as someone else's dependency. However, Yarn 2 is strict about this and it results in a compile-time error.

**Comment by minherz** [comment]
Thank you. So, you are looking to add this type to the list of dependencies in the package.json:
https://github.com/googleapis/nodejs-logging/blob/ee07a7df9bfffc549754dd1915039d846e4c042f/package.json#L47

We have the [package](https://yarnpkg.com/package/@google-cloud/logging) on Yarn 2 for quite some time and this is a first time we get this request. Can you please describe the environment you are running and what error you get at compile time?
We would like to reproduce the problem in order to understand why it wasn't raised before.

**Comment by JustinRWright** [comment]
I also came across this issue after running tsc -p . from a package of mine in a yarn v4 environment:

```
.yarn/berry/cache/@google-cloud-logging-npm-11.0.0-ca229be57b-10c0.zip/node_modules/@google-cloud/logging/build/protos/protos.d.ts:16:23 - error TS2307: Cannot find module 'long' or its corresponding type declarations.

16 import Long = require("long");
                         ~~~~~~

Found 1 error in .yarn/berry/cache/@google-cloud-logging-npm-11.0.0-ca229be57b-10c0.zip/node_modules/@google-cloud/logging/build/protos/protos.d.ts:16
```
**Environment**
"@google-cloud/logging": "^11.0.0",

Typescript: 5.3.2 (Using the yarn pnp sdk)

Yarn -v 4.0.2

**Attempted workaround**
I tried adding "long" as a devDependency: ^5.2.3
(Long now has types built in but google-gax still uses @types/long)

I tried adding @types/long as a devDependency: ^4.0.2

These did not work

**Workaround**
I added this to my project's yarnrc.yml and set the versions as such

packageExtensions:
    "@google-cloud/logging@*":
        peerDependencies:
            "@types/long": "4.0.2"
            
This workaround fixed the issue

**Comment by minherz** [comment]
@losalex is no longer working on this project.

**Comment by xSAVIKx** [comment]
We've also faced this issue recently with Yarn3 and `"@google-cloud/logging": "11.1.0"` version.

We've using typescript, so it actually fails when you run `tsc`

As soon as I added `long` as a dependency it worked.
