### ISSUE TITLE
Just Basic Help

### ISSUE THREAD

**Issue by jessejamesrich** [googleapis/nodejs-logging#1186]
New to the program. I can't even get the most basic features setup on a test environment on Node/React on Mac. Feel I've got this setup properly following the guides, but all I get back is:

```
598 | var kCustomPromisifiedSymbol = typeof Symbol !== 'undefined' ? Symbol('util.promisify.custom') : undefined;
  599 | 
  600 | exports.promisify = function promisify(original) {
> 601 |   if (typeof original !== 'function')
  602 |     throw new TypeError('The "original" argument must be of type Function');
  603 | 
  604 |   if (kCustomPromisifiedSymbol && original[kCustomPromisifiedSymbol]) {
```

```
 21 | const google_auth_library_1 = require("google-auth-library");
  22 | const util_1 = require("util");
  23 | const readFile = util_1.promisify(fs.readFile);
> 24 | function zoneFromQualifiedZone(qualified) {
  25 |     // Some parsing is necessary. Metadata service returns a fully
  26 |     // qualified zone name: 'projects/{projectId}/zones/{zone}'. Logging
  27 |     // wants just the zone part.
```

Forgive my ignorance here, but I'm at a loss. I've done similar setups on Firebase and Admin function without trouble. Any help would be very much appreciated. 

Oh shoot. This is a sample client lib isn't it... ?

**Comment by daniel-sanche** [comment]
Hey, we have some basic code samples in the [README](https://github.com/googleapis/nodejs-logging#using-the-client-library), I'd suggest taking a look there to start out. If you can explain what you're hoping to accomplish, we can try to give more detailed advice as well. Can you post some code snippets that are causing the errors for you?

**Comment by jessejamesrich** [comment]
10-4. Let me revisit this here in a bit. Thanks for the reply. I usually skate through these things.

**Comment by losalex** [comment]
Thanks @daniel-sanche for help - I am closing this issue for now.

@jessejamesrich,
Please let us know if you unblocked or have any other issues.
