### ISSUE TITLE
Add Instance name in the default metadata resource labels

### ISSUE THREAD

**Issue by Abhi347** [googleapis/nodejs-logging#125]
#### Environment details

  - OS: Linux Debian
  - Node.js version: 8.9.4
  - npm version: 6.0.1
  - `@google-cloud/logging` version: 1.2.0

#### Steps to reproduce
Create a log entry to Stackdriver and deploy it to a GCE instance. You can see that the resource flag doesn't have instance name label in it. Due to this when I select `View Logs` option in GCP console near the instance name, it goes to the logs directly, since it filters by resource name, instead of instance_id.  
Please add instance name in the default resource flags too.

**Comment by callmehiphop** [comment]
@JustinBeckwith this reads more like a feature request to me, not a logging expert though, so let me know if you think otherwise!

**Comment by nicoleczhu** [comment]
Hi @Abhi347, I'm working on a PR (see link above) that can easily get this in. The only reservation I have is whether to name  this label `container_name` or `instance_name`.  It's not currently defined by any logging contracts, so there's some flexibility here - but whatever we decide is here to stay.
