### ISSUE TITLE
maxResults in getEntries looks broken

### ISSUE THREAD

**Issue by Raffaello** [googleapis/nodejs-logging#1277]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
This is the client library for . We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.
`Client Library issue`
2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-logging/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
`Nope`
3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: linux
  - Node.js version: 16.13.2
  - npm version: 8.1.2
  - `@google-cloud/logging` version: ^9.9.0"

#### Steps to reproduce

  1. 
  ```js
  const loggingClient = new Logging();
  const [entries] = await loggingClient.getEntries({
        autoPaginate: false,
        //filter: filters.join('\n'),
        maxResults: 5,
    })
    
   expect(entries.length).toBe(5)
  ```
  2.  output:
  ```
      Expected: 5
    Received: 50
  ```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by losalex** [comment]
Thanks @Raffaello for opening this issue - indeed, there is a bug in client library logic where `maxResults` is not propagated. Thats said, even if we fix `maxResult` propagation, still your sample will not work since it will require `autoPaginate` to be `true`. If you want to fetch just up to N results, we might need to make a change to use `listLogEntriesAsync` which returns an iterator, so the caller can stop the iteration whenever they like.
