### ISSUE TITLE
Add support for library instrumentation

### ISSUE THREAD

**Issue by losalex** [googleapis/nodejs-logging#1286]
This feature provides an ability to log extra entry with diagnostics structure which contains logging library information. Such entry is logged only once when first entry is written by a process using logging library.
In the future, the diagnostic record could be extended to include more details about libraries used, runtime environment, etc.
Below is example of how the logging record with diagnostic info looks:

```json
{
 "jsonPayload": {
   "logging.googleapis.com/diagnostic": {
     "instrumentation_source": [
       {
         "name": "nodejs",
         "version": "10.0.1"
       }
     ]
   }
 },
 "insertId": "..........CC_7geD6W7jQV1oz_bQ_ee",
 "severity": "INFO",
 "logName": "projects/startup/logs/hello-log",
}
```

**Comment by losalex** [comment]
Fixed in [1279](https://github.com/googleapis/nodejs-logging/pull/1279) and [1261](https://github.com/googleapis/nodejs-logging/pull/1261)

**Comment by evil-shrike** [comment]
How can I disable outputting those log items?  They just pollute my logs without any added value. It's especially a concern for Cloud Functions - every invocation will create such an entry after first log entry.
