### ISSUE TITLE
npm audit failing

### ISSUE THREAD

**Issue by Lawton** [googleapis/nodejs-logging#1299]
Hi there. 

We are using [logging-bunyan](https://github.com/googleapis/nodejs-logging-bunyan) which in turn depends on this library. 

Our npm audit is failing due to a the following vulnerability in [protobufjs](https://github.com/advisories/GHSA-g954-5hwp-pp24). This appears to be coming from google-gax dependency. There seems to be a fix mentioned in version [3.0.2](https://github.com/googleapis/gax-nodejs/releases/tag/v3.0.2) that updates the dependency on protobufjs to the latest version. 

I'm wondering if it is possible to update the dependency in this library for google-gax to 3.0.2 or later? If it is should a log a separate ticket to have the dependency in logging-bunyan updated for this library?

Thanks!

**Comment by losalex** [comment]
@Lawton , thanks a lot for filing this issue and really sorry for delay - sent PR to update google-gax library. As for other libraries - I will update nodejs-logging-bunyan and nodejs-logging-winston as well
