### ISSUE TITLE
Logging to stdout in Cloud Run creates a JSON object as "message"

### ISSUE THREAD

**Issue by losalex** [googleapis/nodejs-logging#1301]
When enabling structured logging to STDOUT, received structured JSON payload containing an extra "message" key with the original logged message, as well as a "metadata" key of an empty object.
See related bug [704](https://github.com/googleapis/nodejs-logging-winston/issues/704)

**Comment by Allezxandre** [comment]
I have attempted a fix on this branch: https://github.com/prgm-dev/nodejs-logging/commit/a220caea5a4f6e77038b91801889dc308175b539

Been using it in production for about 2 weeks now, but not sure it's the right fix.

Will try to open a PR with these changes this week, but as @losalex remarked in https://github.com/googleapis/nodejs-logging-winston/issues/704, this might be a breaking change for users relying on this outside of Cloud Run.

**Comment by losalex** [comment]
> I have attempted a fix on this branch: [prgm-dev@a220cae](https://github.com/prgm-dev/nodejs-logging/commit/a220caea5a4f6e77038b91801889dc308175b539)
> 
> Been using it in production for about 2 weeks now, but not sure it's the right fix.
> 
> Will try to open a PR with these changes this week, but as @losalex remarked in [googleapis/nodejs-logging-winston#704](https://github.com/googleapis/nodejs-logging-winston/issues/704), this might be a breaking change for users relying on this outside of Cloud Run.

Thank you @Allezxandre - this is very helpful! Indeed - I am looking into your change now and it is very useful, so I am planning also to add the parameter to control this change with default to be set to "off" so it wont break existing clients. Later when we have a major release we might consider turning it "on" by default - let me know if you have any comments

**Comment by losalex** [comment]
Will work to propagate this fix to winston/bunyan as well
