### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer.

### ISSUE THREAD

**Issue by raphaelarias** [googleapis/nodejs-logging#1336]
#### Environment details

  - OS: node:18 or node:18-alpine (running with Docker on Cloud Run)
  - Node.js version: Node.js v18.9.0
  - `@google-cloud/logging` version: 10.0.4

#### Steps to reproduce

I'm finding problematic to pin-point exactly where it's happening, as in my local machine I've experienced no problems (I've tested with Mac OS and same Node version).

In this Nest (@nestjs/cli: "^8.0.0") application, I've implemented logging with `@google-cloud/logging'`, when deployed to Cloud Run, a request is fulfilled, and immediately an exception is thrown:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object at new NodeError (node:internal/errors:393:5) at Function.byteLength (node:buffer:740:11) at BufferWriter.write_string_buffer [as string] (/node_modules/protobufjs/src/writer_buffer.js:70:27) at Type.LogEntry$encode [as encode] (eval at Codegen (/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:25:15) at Type.encode_setup [as encode] (/node_modules/protobufjs/src/type.js:485:25) at BundleDescriptor.getByteLength [as byteLengthFunction] (/node_modules/@google-cloud/logging/node_modules/google-gax/build/src/grpc.js:415:28) at /node_modules/@google-cloud/logging/node_modules/google-gax/build/src/bundlingCalls/bundleExecutor.js:83:46 at Array.forEach (<anonymous>) at BundleExecutor.schedule (/node_modules/@google-cloud/logging/node_modules/google-gax/build/src/bundlingCalls/bundleExecutor.js:82:22) at /node_modules/@google-cloud/logging/node_modules/google-gax/build/src/bundlingCalls/bundleApiCaller.js:43:26 at OngoingCallPromise.call (/node_modules/@google-cloud/logging/node_modules/google-gax/build/src/call.js:67:27) at BundleApiCaller.call (/node_modules/@google-cloud/logging/node_modules/google-gax/build/src/bundlingCalls/bundleApiCaller.js:42:16) at /node_modules/@google-cloud/logging/node_modules/google-gax/build/src/createApiCall.js:81:30 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This is my code that inits the `ErrorReporting`:

```
const logging = new Logging({
      projectId: process.env.GOOGLE_CLOUD_PROJECT,
    });

const errors = new ErrorReporting({
      projectId: process.env.GOOGLE_CLOUD_PROJECT,
      reportMode: 'always',
      serviceContext: {
        service: INSTANCE_SERVICE_NAME,
        version: INSTANCE_SERVICE_REVISION,
      },
    });
```

![image](https://user-images.githubusercontent.com/5008166/189471583-a39f0bdd-a78f-4f1f-ac41-029dd9ecca33.png)

Updating to the version *10.0.8* kinda fixes the issue. I believe the PR in relation to `google-gax` may have fixed it (?).

So instead of throwing the error above, it's now a WARNING, and the logging does seem to work:

```
Warning: Cannot encode protobuf.js object: {"timestamp":{"seconds":1662792503,"nanos":108000040},"resource":{"type":"cloud_run_revision"},"labels":{"service_name":"core-v1","revision_name":"core-v1-00018-soh","labels":{}},"severity":"INFO","httpRequest":{"requestMethod":"GET","requestUrl":"/v1/health","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36","referer":"","status":304,"remoteIp":"::ffff:169.254.1.1"},"insertId":"..........DDnHbSjXGCs7YSO5xbnyu8","textPayload":"GET 304 /v1/health"}: TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received an instance of Object
```

![image](https://user-images.githubusercontent.com/5008166/189472683-c5f2504a-2e18-46e2-8dca-b23e01ae6eef.png)

**Comment by losalex** [comment]
Thanks @raphaelarias for reaching out and providing great details on an issue!
It seems that there is a problem with `"labels":{"service_name":"core-v1","revision_name":"core-v1-00018-soh","labels":{}}` which has nested `"labels": {}` as non-string object. 
We are currently looking to understand a source for a problem, but it would be really helpful also if you can share the code you use to write those log entries.

**Comment by losalex** [comment]
@raphaelarias , please let me know if you can share a code that you use to generate the logs. If you feel that there is no further help required, please let me know so I can close the issue - thanks!
