### ISSUE TITLE
 Inconsistent/Incorrect Typing of LogEntry.HttpRequest.Latency 

### ISSUE THREAD

**Issue by mantism** [googleapis/nodejs-logging#1417]
I want to log http requests to LogExplorer by printing LogEntry objects to stdout. This works for the most part, but I've noticed latency doesn't get automatically parsed in Log Explorer from the HttpRequest object. 

The [LogEntry.HttpRequest documentation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest) lists the JSON representation as having `latency` by of type `string`, but the [proto and other types for HttpRequest]( https://github.com/googleapis/nodejs-logging/blob/140d3844a62e0b46a09528e82eae631948f3a79e/protos/google/logging/type/http_request.proto#L74) have latency as a Duration with seconds and nano. 

As a result, when logged to stdout, Log Explorer leaves the latency object in the jsonPayload field as opposed to the httpRequest field of the LogEntry. 

- Any error messages you're getting
    - No error messages

1) Is this a client library issue or a product issue?
- client library

2) Did someone already solve this?
- I haven't found anything else reporting this as an issue

3) Do you have a support contract?
N/A

#### Environment details

  - OS: Linux, MacOs
  - Node.js version: 16.20.0
  - pnpm version: 7.11.0
  - `@google-cloud/logging` version: 10.3.2

#### Steps to reproduce

  1. Create an object of type LogEntry with an httpRequest
  2. console.log() the LogEntry
  3. Check LogExplorer and see that the LogEntry has latency in jsonPayload instead of httpRequest i.e.
  
```json
{
  "logName": "example-logName",
  "timestamp": "1234",
  "severity":  "INFO"
  "insertId":  "..1234",
  "httpRequest": {
      "requestMethod": "GET",
      "requestUrl": "example.com/api/example",
      "protocol": "http",
      // Expected latency here
   }
  "jsonPayload": {
      // Expected to see this in httpRequest
      "latency": {
         "seconds": 1
         "nanos": 2
      }
  }
}
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by losalex** [comment]
@mantism , thank you very much for opening the issue and sorry for late response!
Indeed, documentation is confusing with respect of `latency` being a `string` type. Thats said, if I execute following code:

```js
log.write(logging.entry({
  httpRequest: {
    requestMethod: 'GET',
    requestUrl: 'http://some-url.com',
    status: 200,
    latency: {
      seconds: 1,
      nanos: 2,
   },
 
  }}, {message: "This is an info 1"}));
```

I see that latency generated properly in Logs Explorer:

<img width="330" alt="image" src="https://github.com/googleapis/nodejs-logging/assets/90795544/5cd9b5c8-28c2-4486-90e8-0084ded5979f">

Would you be able to share the code snippet you used to repro a problem? 
Thanks!

**Comment by losalex** [comment]
Closing this due to no response - please feel free to reactivate if there are any questions or new findings.
