### ISSUE TITLE
`@google-cloud/logging-min` not being released

### ISSUE THREAD

**Issue by vlinder** [googleapis/nodejs-logging#1496]
It seems that the package `@google-cloud/logging-min` is not being kept up to date and released at the same time as `@google-cloud/logging`

`@google-cloud/loggin-min` still has a dependency on an old version of `'google-gax': '^3.5.2'` which now has a security vulnerability through `protobufjs`.

Would it be possible to release `@google-cloud/logging-min` together with `@google-cloud/logging`?

**Comment by klon** [comment]
@cindy-peng What is going on here, why is it taking months to get this fixed? There is a critical vulnerability in a dependency that is not getting fixed due to this seemingly trivial task.

**Comment by cindy-peng** [comment]
Sorry about the late response! We have released a newer version for `@google-cloud/logging-min`: https://www.npmjs.com/package/@google-cloud/logging-min?activeTab=readme
Please retry and let us know if this resolves the vulnerability issue. Thanks!

**Comment by cindy-peng** [comment]
Closing issue as the new version has been released and should resolve the vulnerability.
