### ISSUE TITLE
Unhandled TypeError: obj.hasOwnProperty crashes app

### ISSUE THREAD

**Issue by ericrwolfe** [googleapis/nodejs-logging#178]
#### Environment details

  - OS: Firebase functions (SDK 2.0.2)
  - Node.js version: 8.x
  - npm version: ?
  - `@google-cloud/logging` version: @google-cloud/logging-bunyan (0.8.2)

#### Steps to reproduce

I'm seeing a problem while using @google-cloud/logging-bunyan (0.8.2) within Firebase functions (SDK 2.0.2) and express-bunyan-logger (1.3.3) that causes an unhandled promise rejection and a subsequent application crash.

The error trace starts out looking like the trace reported here https://github.com/googleapis/gax-nodejs/issues/164.

I dug in a bit and it looks like within `Log.prototype.decorateEntries_`, `entry.toJSON()` throws a `TypeError: obj.hasOwnProperty is not a function` error:
https://github.com/googleapis/nodejs-logging/blob/7feb300801506bfe0613cec281e5df28faa9d13a/src/log.js#L736-L748

The `entry` object, which comes via express-bunyan-logger, looks like so:
```js
entry.data = {"name":"footpath-api","hostname":"erwrmbp","pid":64383,"req_id":"0f3c0d73-e736-4777-8d4a-c702ea905ad4","level":30,"remote-address":"::ffff:127.0.0.1","ip":"::ffff:127.0.0.1","method":"GET","url":"/v2/ping","referer":"-","user-agent":{"family":"Safari","major":"11","minor":"1","patch":"1","device":{"family":"Other","major":"0","minor":"0","patch":"0"},"os":{"family":"Mac OS X","major":"10","minor":"13","patch":"5"}},"http-version":"1.1","response-time":3.104447,"response-hrtime":[0,3104447],"status-code":200,"req-headers":{"host":"localhost:3000","upgrade-insecure-requests":"1","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15","accept-language":"en-us","accept-encoding":"gzip, deflate","connection":"keep-alive"},"res-headers":{"x-powered-by":"Express","cache-control":"private, no-cache, no-store, must-revalidate","expires":"-1","pragma":"no-cache","content-type":"application/json; charset=utf-8","content-length":"16","etag":"W/\"10-oV4hJxRVSENxc/wX8+mA4/Pe4tA\"","vary":"Accept-Encoding"},"req":{"method":"GET","url":"/ping","headers":{"host":"localhost:3000","upgrade-insecure-requests":"1","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15","accept-language":"en-us","accept-encoding":"gzip, deflate","connection":"keep-alive"},"remoteAddress":"::ffff:127.0.0.1","remotePort":49188},"res":{"statusCode":200,"header":"HTTP/1.1 200 OK\r\nX-Powered-By: Express\r\nCache-Control: private, no-cache, no-store, must-revalidate\r\nExpires: -1\r\nPragma: no-cache\r\nContent-Type: application/json; charset=utf-8\r\nContent-Length: 16\r\nETag: W/\"10-oV4hJxRVSENxc/wX8+mA4/Pe4tA\"\r\nVary: Accept-Encoding\r\nDate: Sat, 28 Jul 2018 21:28:12 GMT\r\nConnection: keep-alive\r\n\r\n"},"incoming":"<--","time":"2018-07-28T21:28:12.049Z","v":0,"message":"::ffff:127.0.0.1 <-- GET /v2/ping HTTP/1.1 200 16 - Safari 11.1 Mac OS X 10.13.5 3.104447 ms"};
entry.metadata = {"timestamp":"2018-07-28T21:28:12.049Z","severity":"INFO","insertId":"..........Qd_rUWirSCtdHC_7ipjBiZ"};
```

However, just up the stack in `Log.writeWithResource()` the error goes unhandled:
https://github.com/googleapis/nodejs-logging/blob/7feb300801506bfe0613cec281e5df28faa9d13a/src/log.js#L696-L702
`decoratedEntries` and the corresponding `reqOptions.entries` remain `undefined` while passed to `self.logging.request()`.

This causes the `google-gax` library to trip up on this missing `entries` array, when it throws a `TypeError: Cannot read property 'length' of undefined` on this line: 
https://github.com/googleapis/gax-nodejs/blob/3360c3ea0ab254da91c42ac8b7d03d3bbb6df402/src/bundling.ts#L379-L380

The error goes unhandled in promise, and it crashes the app.

**Comment by ericrwolfe** [comment]
Notably, removing the [express-buyan-logger](https://github.com/villadora/express-bunyan-logger) middleware works around the issue, so it seems to be related to how their log entry is formatted.

**Comment by stephenplusplus** [comment]
Thank you for the detailed report! Is it possible you could prepare a "clone and run" reproduction sample? I've tried reproducing from the `entry.data` and `entry.metadata` objects you provided, but it still succeeded, so the real environment is probably crucial.

**Comment by ericrwolfe** [comment]
@stephenplusplus Here's a sample repo you can use to reproduce the error: https://github.com/ericrwolfe/firebase-functions-logging-test 

Depending on how you're debugging you might want to add a hook in app.js for the unhandled promise rejection:
```js
process.on('unhandledRejection', (reason, p) => {
  console.error({
    promise: p,
    reason,
  }, 'Unhandled promise rejection');
});
```

**Comment by stephenplusplus** [comment]
Thank you very much! I think I've got it: https://github.com/googleapis/nodejs-logging/issues/178
