### ISSUE TITLE
Switch this library to TypeScript

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging#194]
Regression fixed by #193 could have been avoided if this library was in TypeScript. There is little safety without types.

**Comment by JustinBeckwith** [comment]
Blocked on https://github.com/googleapis/gapic-generator/issues/2054

**Comment by JustinBeckwith** [comment]
This is currently blocked on #264.  After that's complete, we need to add the `types` directive to the `package.json`, and do some sanity testing to make sure the packed module supports types as expected.

**Comment by JustinBeckwith** [comment]
So this is in TypeScript now :) Next step is to land noImplicitAny so the types are actually good :P
