### ISSUE TITLE
Write correlation-id to log entries when available

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-logging#23]
_From @JustinBeckwith on May 12, 2017 14:58_

By writing a correlation-id into the logging metadata, users can get request-correlated logs in pantheon.  See https://gist.github.com/JustinBeckwith/43dd04cfbc4551ddd8996a5b803da0b0 for details.  

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2304_

**Comment by stephenplusplus** [comment]
_From @landrito on August 9, 2017 22:26_

@JustinBeckwith I am having trouble seeing the gist.

**Comment by stephenplusplus** [comment]
@JustinBeckwith @ofrobots any elaboration would be appreciated!

**Comment by ofrobots** [comment]
I believe this has been implemented in `logging-{winston,bunyan}` through https://github.com/googleapis/nodejs-logging-winston/commit/4b2da1128d656eab8c6492d10b1b201e7bcc3e9f (and similar for bunyan).

**Comment by stephenplusplus** [comment]
@JustinBeckwith is this still wanted, given what @ofrobots said above? The answer may be in that secret gist :)

**Comment by JustinBeckwith** [comment]
I shared a doc with you :)

**Comment by ofrobots** [comment]
What work is outstanding here?

**Comment by stephenplusplus** [comment]
I am still awaiting approval for viewing the doc :)

**Comment by JustinBeckwith** [comment]
Eugh sorry.  I shared a copy of the doc with you.

**Comment by stephenplusplus** [comment]
Per https://github.com/googleapis/nodejs-logging/pull/102, it seems like we don't want this. If we do, well... just re-open!
