### ISSUE TITLE
[GKE] no such Type or Enum 'google.api.MonitoredResourceMetadata' in Type .google.logging.v2.LogEntry

### ISSUE THREAD

**Issue by patkoeller** [googleapis/nodejs-logging#241]
#### Environment details

  - OS: Docker - node:8.9-alpine - Alpine Version 3.6.2 - Google Kubernetes Engine (important)
  - Node.js version: 8.9.4
  - npm version: 5.6.0
  - `@google-cloud/logging` version: 4.0.1

#### Steps to reproduce

  1. Setup a kubernetes server that uses logging
  2. Attempt to log an entry

Minimal reproduction code is provided below, i attempt to pull the logging proto and MonitoredResourceMetadata proto directly, however the google.api.MonitoredResourceMetadata is not defined. This code works perfectly fine on a compute engine or running locally.

I am not sure how to figure out what is causing a difference on GKE only and not on other environments. I manually inspected various files and ensured that the proto files exist and have tested directly loading the proto file using protobuf.loadSync which does work.

```
const protobuf = require('protobufjs');
const path = require('path');
const gax = require('google-gax');
const {Logging} = require('@google-cloud/logging');

let protoFilesRoot = new gax.GoogleProtoFilesRoot();
protoFilesRoot = protobuf.loadSync(
  path.join(
    __dirname,
    'node_modules',
    '@google-cloud',
    'logging',
    'protos',
    'google/logging/v2/logging.proto'
  ),
  protoFilesRoot
);

// Your Google Cloud Platform project ID
const projectId = '########';

// Creates a client
const logging = new Logging({
  projectId: projectId,
});

// The name of the log to write to
const logName = 'pat-test';
// Selects the log to write to
const log = logging.log(logName);
// The data to write to the log
const text = 'pat-test!';
// The metadata associated with the entry
const metadata = {resource: {type: 'global'}};
// Prepares a log entry
const entry = log.entry(metadata, text);
log
  .write(entry)
  .then(() => {
    console.log(`Logged: ${text}`);
    console.log("LogEntry",JSON.stringify(protoFilesRoot.lookup('google.logging.v2.LogEntry')));
    console.log("MonitoredResourceMetadata",JSON.stringify(protoFilesRoot.lookup('google.api.MonitoredResourceMetadata')));

  })
  .catch(err => {
    console.error('ERROR:', err);
    console.log("LogEntry",JSON.stringify(protoFilesRoot.lookup('google.logging.v2.LogEntry')));
    console.log("MonitoredResourceMetadata",JSON.stringify(protoFilesRoot.lookup('google.api.MonitoredResourceMetadata')));

  });

//Used to keep kubernetes pod running and prevents the crash loopback for testing
var http = require('http');
var express = require( "express" );
var app = express();
app.get("/",function(req,res,next){
  res.status(200).json({status:'healthy'})
})
var server = http.createServer(app);
server.listen(80,function(){
})
```
Results:
> LogEntry {"oneofs":{"payload":{"oneof":["protoPayload","textPayload","jsonPayload"]}},"fields":{"logName":{"type":"string","id":12},"resource":{"type":"google.api.MonitoredResource","id":8},"protoPayload":{"type":"google.protobuf.Any","id":2},"textPayload":{"type":"string","id":3},"jsonPayload":{"type":"google.protobuf.Struct","id":6},"timestamp":{"type":"google.protobuf.Timestamp","id":9},"receiveTimestamp":{"type":"google.protobuf.Timestamp","id":24},"severity":{"type":"google.logging.type.LogSeverity","id":10},"insertId":{"type":"string","id":4},"httpRequest":{"type":"google.logging.type.HttpRequest","id":7},"labels":{"keyType":"string","type":"string","id":11},"metadata":{"type":"google.api.MonitoredResourceMetadata","id":25},"operation":{"type":"LogEntryOperation","id":15},"trace":{"type":"string","id":22},"spanId":{"type":"string","id":27},"sourceLocation":{"type":"LogEntrySourceLocation","id":23}}}
> 
> MonitoredResourceMetadata null
> 
> ERROR: Error: no such Type or Enum 'google.api.MonitoredResourceMetadata' in Type .google.logging.v2.LogEntry
>    at Type.lookupTypeOrEnum (/home/node/node_modules/protobufjs/src/namespace.js:410:15)
>    at Field.resolve (/home/node/node_modules/protobufjs/src/field.js:265:94)
>    at Type.set (/home/node/node_modules/protobufjs/src/type.js:177:38)
>    at Type.get (/home/node/node_modules/protobufjs/src/type.js:155:45)
>    at Field.resolve (/home/node/node_modules/protobufjs/src/field.js:314:21)
>    at Type.setup (/home/node/node_modules/protobufjs/src/type.js:435:41)
>    at Type.encode_setup [as encode] (/home/node/node_modules/protobufjs/src/type.js:485:17)
>    at BundleDescriptor.getByteLength [as byteLengthFunction] (/home/node/node_modules/google-gax/build/src/grpc.js:317:28)
>    at /home/node/node_modules/google-gax/build/src/bundling.js:338:47
>    at Array.forEach (<anonymous>)

NPM Install log in case it helps.

> npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
> npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=0.3.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
> npm WARN notice [SECURITY] growl has the following vulnerability: 1 critical. Go here for more details: https://nodesecurity.io/advisories?search=growl&version=1.9.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
> 
> > grpc@1.15.1 install /builds/apartmentjet/aj-test/node_modules/grpc
> > node-pre-gyp install --fallback-to-build --library=static_library
> 
> node-pre-gyp WARN Using needle for node-pre-gyp https download 
> [grpc] Success: "/builds/apartmentjet/aj-test/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-musl/grpc_node.node" is installed via remote
> 
> > protobufjs@6.8.8 postinstall /builds/apartmentjet/aj-test/node_modules/protobufjs
> > node scripts/postinstall
> 
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN aj-ms-template@1.0.0 No repository field.
> npm WARN aj-ms-template@1.0.0 No license field.

**Comment by ajaaym** [comment]
@patkoeller I tried with versions you mentioned and it worked fine. If this is still an issue, can you please share your docker file?

**Comment by callmehiphop** [comment]
Haven't seen much activity here lately, I'm going to close this out, but if anyone continues to experience this let us know and we'll be happy to re-open. 😎
