### ISSUE TITLE
windows kokoro builds timeout during npm install

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging#303]
Example [this build](https://source.cloud.google.com/results/invocations/348bb585-efa3-4dbc-b7df-8c38157a01a5/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fgoogleapis%2Fnodejs-logging%2Fpresubmit%2Fwindows%2Ftest/log) on #298.

**Comment by JustinBeckwith** [comment]
I haven't seen this is many runs, so I'm gonna go ahead and close this one.  If it comes back, we can re-open :)
