### ISSUE TITLE
HTTPS_PROXY with HTTP Proxy fail to connect

### ISSUE THREAD

**Issue by refextu** [googleapis/nodejs-logging#350]
#### Environment details
  - OS: all
  - Node.js version: 8.11.*
  - npm version: 5.6.0
  - `@google-cloud/logging` version: 4.1.1

#### Steps to reproduce

1. Setup a http Proxy
```docker run --publish 3128:3128 sameersbn/squid:3.3.8-23```

2. Start a logging instance with HTTPS_PROXY env
```HTTPS_PROXY=http://proxy... node script.js```

3. try to log
```javascript
const { Logging } = require('@google-cloud/logging');

if (process.env.GOOGLE_APPLICATION_CREDENTIALS) {
  const logging = new Logging({
    projectId: 'process.env.PROJECTID',
  });

  const logName = 'my-log';
  const log = logging.log(logName);


  const metadata = {
    resource: { type: 'global' },
  };

  const entry = log.entry(metadata, { logDate: Date.now() });
  log.info(entry, console.log);
};
```

#### Expected

Logging of the Logdata

#### Actual

Receiving Error:

```
Auth error:Error: write EPROTO 4409435584:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

{ Error: 14 UNAVAILABLE: Getting metadata from plugin failed with error: write EPROTO 4409435584:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
    at Object.exports.createStatusError (/Users/name/source/project/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/Users/name/source/project/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/Users/name/source/project/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/name/source/project/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/name/source/project/node_modules/grpc/src/client_interceptors.js:841:24)
```

It seems that the Error is based in GRPC and there is no support for proxies.

The only alternative in my case is to use the REST API direct, but it is not recommended.

Similar issue but for axios: https://github.com/googleapis/nodejs-storage/issues/277

**Comment by stephenplusplus** [comment]
Thank you for reporting! I'm currently digging into this one, and will keep you posted.

**Comment by refextu** [comment]
just remembered this: https://github.com/googleapis/gax-nodejs/issues/141 which also relates to gRPC

**Comment by stephenplusplus** [comment]
Thanks @refextu. I believe https://github.com/googleapis/gax-nodejs/issues/141 can track this for us.

**Comment by ajaaym** [comment]
@refextu can you please try setting both env variable ```https_proxy``` & ```HTTPS_PROXY``` GRPC uses [https_proxy](https://github.com/grpc/grpc/blob/53657b5de385ffc54e33899b3f2a87ff78d2952b/src/core/ext/filters/client_channel/http_proxy.cc#L53) and authentication which goes through normal node request uses HTTPS_PROXY. Its working fine for me following your steps, below is the log.

```
1550772966.261      1 172.17.0.1 TCP_MISS/503 0 CONNECT metadata.google.internal:443 - HIER_NONE/- -
1550772966.277      0 172.17.0.1 TCP_MISS/503 0 CONNECT metadata.google.internal:443 - HIER_NONE/- -
1550772966.787      0 172.17.0.1 TCP_MISS/503 0 CONNECT metadata.google.internal:443 - HIER_NONE/- -
1550772968.293      0 172.17.0.1 TCP_MISS/503 0 CONNECT metadata.google.internal:443 - HIER_NONE/- -
1550772968.298      0 172.17.0.1 TCP_MISS/503 0 CONNECT metadata.google.internal:443 - HIER_NONE/- -
1550772968.302      0 172.17.0.1 TCP_MISS/503 0 CONNECT metadata.google.internal:443 - HIER_NONE/- -
1550772968.811      0 172.17.0.1 TCP_MISS/503 0 CONNECT metadata.google.internal:443 - HIER_NONE/- -
1550772970.322      0 172.17.0.1 TCP_MISS/503 0 CONNECT metadata.google.internal:443 - HIER_NONE/- -
1550772970.766    177 172.17.0.1 TCP_MISS/200 4704 CONNECT www.googleapis.com:443 - HIER_DIRECT/172.217.10.138 -
1550772971.031    540 172.17.0.1 TCP_MISS/200 4263 CONNECT logging.googleapis.com:443 - HIER_DIRECT/172.217.10.138 -

```

**Comment by refextu** [comment]
@ajaaym I can confirm that this working as expected.

`HTTPS_PROXY=http://localhost:3128 node script.js`
and 
`https_proxy=http://localhost:3128 node script.js`
logs perfectly to google cloud
