### ISSUE TITLE
Node Event Loop blocking

### ISSUE THREAD

**Issue by sarkistlt** [googleapis/nodejs-logging#357]
Hey, I really like the library, but I noted in my metrics that it increases node event loop lag. Example:

```
{
        "stack": [
          "    at new Promise (<anonymous>)", 
          "    at new WrappedPromise (/app/node_modules/async-listener/es6-wrapped-promise.js:9:7)", 
          "    at Promise.then (<anonymous>)", 
          "    at Promise.wrappedThen (/app/node_modules/async-listener/index.js:524:27)", 
          "    at GoogleAuth.getProjectId (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:73:38)", 
          "    at prepareGaxRequest (/app/node_modules/@google-cloud/logging/src/index.ts:741:17)", 
          "    at makeRequestCallback (/app/node_modules/@google-cloud/logging/src/index.ts:765:7)", 
          "    at Logging.request (/app/node_modules/@google-cloud/logging/src/index.ts:738:7)", 
          "    at writeWithResource (/app/node_modules/@google-cloud/logging/src/log.ts:673:22)", 
          "    at metadata_1.getDefaultResource.then (/app/node_modules/@google-cloud/logging/src/log.ts:646:19)", 
          "    at propagateAslWrapper (/app/node_modules/async-listener/index.js:504:23)", 
          "    at /app/node_modules/async-listener/glue.js:188:31", 
          "    at /app/node_modules/async-listener/index.js:541:70", 
          "    at /app/node_modules/async-listener/glue.js:188:31"
        ], 
        "time": 206.7354169921875 // event loop lag
      }
```

is it possible that this library would cause delay in event loop? Didn't check the source code, but if it uses bunyan, or JSON.stringify for logging then it definitely will.

**Comment by seriousManual** [comment]
I'm curious, how are you measuring the lag of your event loop?

**Comment by bcoe** [comment]
@sarkistlt I've measured the logging library, as things stand today, bootstrapping the library has no (or negligible) effect on the event loop. I measured the event loop lag like so (CC: @seriousManual):

```js
const { monitorEventLoopDelay } = require('perf_hooks');
const h = monitorEventLoopDelay({ resolution: 20 });
h.enable();
let count = 0;
const id = setInterval(() => {
  if (count >= 20) {
    console.info(`outputting event loop delay:`)
    h.disable();
    console.log(h.min);
    console.log(h.max);
    console.log(h.mean);
    console.log(h.stddev);
    console.log(h.percentiles);
    console.log(h.percentile(50));
    console.log(h.percentile(99));
    clearInterval(id);
  }
  count++;
}, 1000);
```

You can [read documentation on this approach here](https://nodejs.org/api/perf_hooks.html#perf_hooks_perf_hooks_monitoreventloopdelay_options).

## Your 200ms value

I believe where your `206ms` value is coming from, is the time that it takes to send the log line to our upstream API. This matches the measurements I see locally:

```js
  // Writes the log entry
  setInterval(async () => {
    const start = Date.now();
    await log.write(entry);
    const stop = Date.now();
    console.log(`time to write = ${stop - start}`);
  }, 2000)
```

This delay doesn't relate to `JSON.stringify` or `bunyan`, rather it's the `gRPC` request being made to the stackdriver service.

## Addressing Latency Issues 

If the `200ms`  latency is a problem, we recommend batching writes together. [I've opened a PR with a toy example of how this can be achieved](https://github.com/googleapis/nodejs-logging/pull/528).

**Comment by sarkistlt** [comment]
@bcoe thanks for the detailed explanation. Sorry didn't reply back on this issue. In my case cause of event-loop delay was remote call to 3d party service on PHP that couldn't process parallel requests fast enough, and sometime was causing a huge event-loop delay. Probably by overloading network I/O thread pool and delaying entire loop.

**Comment by seriousManual** [comment]
thanks @bcoe! 
I didn't know that there's a built in primitive that allows for this kind of statistics!
