### ISSUE TITLE
stackdriver errors likely caused by system tests

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-logging#417]
We receive several of these emails per day. By the project name and the generated sink name I suspect it is something created in the system tests for logging, and deleted incorrectly or in a wrong order. Can someone please investigate?

Thank you!

![image](https://user-images.githubusercontent.com/4015807/54048500-d8cd3780-418e-11e9-85b0-f1040fa4aa43.png)

The troubleshooting link from the email points [here](https://cloud.google.com/logging/docs/export/configure_export_v2#troubleshooting).

**Comment by JustinBeckwith** [comment]
@stephenplusplus mind taking a look here?

**Comment by stephenplusplus** [comment]
@alexander-fenster has this still been happening? If so, would you mind sharing an updated copy of the email?

**Comment by alexander-fenster** [comment]
Still receiving several of those every day :) 

![image](https://user-images.githubusercontent.com/4015807/74271538-e9046580-4cc1-11ea-84ae-cb46acb32a86.png)

**Comment by stephenplusplus** [comment]
PR over here: #706
