### ISSUE TITLE
Question: how to debug the logger itself

### ISSUE THREAD

**Issue by polymorph-andrel** [googleapis/nodejs-logging#438]
Hi everyone

I have configured Winston to use this Stackdriver transport according to the documentation, but it doesn't appear to work. The reason I say this is because I can see the console logging, but nothing on Stackdriver. Is there a way to enable additional diagnostic output of the logger itself to help me diagnose the problem?

Thanks in advance for any help, much appreciated.

**Comment by stephenplusplus** [comment]
@DominicKramer under that scenario, what is the service account/credential availability? Should the auth library be picking it up from an env var, or something else?

**Comment by DominicKramer** [comment]
@JustinBeckwith thanks for moving the issue for me.

There is an issue with the GitHub issue mover [https://github-issue-mover.appspot.com/](https://github-issue-mover.appspot.com/) used to move this issue.  I have reached out to the maintainer, and I'm waiting to hear back.

**Comment by DominicKramer** [comment]
I'm not sure what the service account/credential availability is under GCE?  If anything special is needed from the user in terms of setup, it probably should be documented in the `@google-cloud/loggin` GitHub repo.

**Comment by stephenplusplus** [comment]
GCE should be working fine, but the quirk might be the Docker image deployed to GCE. @JustinBeckwith do you know anything about if automatic authentication is expected in that environment?

**Comment by DominicKramer** [comment]
I agree that I think its the Container Optimized OS that is causing issues.  Another customer reported using the logging library on GCE with Ubuntu and the logs appeared correctly.

**Comment by stephenplusplus** [comment]
@polymorph-andrel while we try to sort out the underlying cause of this issue, you should be able to resolve this by creating a service account and uploading the JSON key file with your app. You can then set the environment variable `GOOGLE_APPLICATION_CREDENTIALS` with the path to that file. Let me know if you have any issues getting that set up. Here's a guide on how to generate that JSON key file: https://cloud.google.com/docs/authentication/getting-started

Thanks for your patience!

**Comment by polymorph-andrel** [comment]
Hi @stephenplusplus. Thanks for helping out. Apologies for my slow response rate on this, we've been deprioritizing this. I'll try your suggestion to see if that helps.

This is why loggers themselves should have a debug mode that pushes diagnostic info to the console. Fiddling in the dark for a switch is no fun.

**Comment by polymorph-andrel** [comment]
Hi guys! Good news, adding the GOOGLE_APPLICATION_CREDENTIALS pointed to a JSON file and setting the serviceContext with a serviceName and version number got all the bits to work as expected. Would you like me to close this issue? 

Thanks again.

**Comment by bcoe** [comment]
@polymorph-andrel awesome, I'm glad you're unblocked. I'll close the issue, but we'll be keeping an eye on how often this category of issue crops up. It's potentially indication of parts of APIs that we could better document.
