### ISSUE TITLE
Signature for `log.write`

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging#441]
`Log.prototype.write` has the following signatures:

```ts
  write(entry: Entry|Entry[], options?: WriteOptions): Promise<ApiResponse>;
  write(
      entry: Entry|Entry[], options: WriteOptions,
      callback: ApiResponseCallback): void;
  write(entry: Entry|Entry[], callback: ApiResponseCallback): void;
  write(
      entry: Entry|Entry[],
      optionsOrCallback?: WriteOptions|ApiResponseCallback,
      cb?: ApiResponseCallback): void|Promise<ApiResponse> {
```

Consumer code in `logging-bunyan` has a path that calls `write(entry)`. That is, no callback may be provided. This works, today, but fails to compile once `logging-bunyan` starts to use types from this module.

When there is no callback provided, what should be the behavior? I am not sure returning a promise would be the right answer as there is no way for anyone to handle a rejection on that promise (new (to me) rule of thumb: don't promise to someone not expecting a promise).

**Comment by kjin** [comment]
I would consider immediately catching and swallowing any rejections from the returned Promise to be equivalent to not providing a callback to a function. Do users actually get this method directly or are usages of `Log.prototype.write` wrapped in the Bunyan logging transport library?

**Comment by ofrobots** [comment]
This seems to have been an oversight in the types for the `logging-bunyan` module. https://github.com/googleapis/nodejs-logging-bunyan/pull/287.
