### ISSUE TITLE
Wrong types for `Entry`

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging#442]
Consider the constructor for `Entry`.

```ts
class Entry {
  // ...
  constructor(metadata?: LogEntry, data?: Data) {
    this.metadata = extend(
        {
          timestamp: new Date(),
        },
        metadata);
```

It expects a `LogEntry` typed `metadata` value to be passed in. Historically this value has accepted a `timestamp` property with a JS `Date` value in it. You can see that internally it expects the `timestamp` to be a JavaScript `Date` as well. `logging-bunyan` passes in a JS `Date` as well.

The problem is that `LogEntry` type doesn't accept `Date` as a value for `timestamp`.

**Comment by ofrobots** [comment]
In the same vein, it seems that `severity` field on `LogEntry` has types that are too strict.

The following errors in `nodejs-logging-bunyan`.

```ts
new Entry({ severity: 'INFO'});
```

**Comment by callmehiphop** [comment]
[Oof](https://github.com/googleapis/nodejs-logging/blob/master/proto/logging.d.ts#L1708), looks like maybe we shouldn't be using the generated type there.
