### ISSUE TITLE
Huge delay to push logs in Stackdriver Log Viewer

### ISSUE THREAD

**Issue by Quentintin** [googleapis/nodejs-logging#47]
Hello,

I've got an issue. I implement "Quickstart" with 'Hello world' code in my project. Logs are correctly send to Stackdriver Logging, but logs displayed about 2m30 after sending in the viewer. It's not really real-time ...
How to fix it ?

Here's my log : 
>{
     insertId:  "..........4PLP5vfgC7BQDghmfONDf5"  
     logName:  "projects/project-id/logs/my-log"  
     receiveTimestamp:  "2017-12-13T15:18:46.985705438Z"  
       resource: {…}  
       textPayload:  "Hello, world!"  
       timestamp:  "2017-12-13T15:21:10.938999891Z"  
}

I've got a free user account currently.

#### Environment details

  - OS: Debian 8.5 Jessie
  - Node.js version: 6.2.2
  - npm version: 5.6.0
  - @google-cloud/logging version: 1.1.1

#### Steps to reproduce
...

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
Sorry to hear about the long delay. @ofrobots -- is there any batching logic or something similar that could explain this? Or is this an upstream issue the Logging team should look at?

**Comment by Quentintin** [comment]
I'm thinking about a priority level. 

I didn't fill billing information, i'm free user and I use "local" way of logging. I expect to be the last in queue of priority

**Comment by Quentintin** [comment]
I succes to find a solution.

I just noticed that my server have time shift on its local datetime ... about 2 min 30 in the future
So I fixed NTP settings and restart ntp service. 

When server's datetime was set as the same datetime as my computer, I get my logs on Logging StackDriver a couple secondes after my node app.

Is it a normal behaviour ?

**Comment by stephenplusplus** [comment]
I don't believe it's something we can control in this library, but that would be a good question for StackOverflow. Here are the tags if you want to get the attention of the right people: https://stackoverflow.com/questions/tagged/google-cloud-platform+node.js+logging -- if it does turn out that there's something we can do from here, we will re-open the issue.

If you post on StackOverflow, please link back so anyone interested can follow along. Thanks!
