### ISSUE TITLE
should use req.originalUrl for express requestUrl

### ISSUE THREAD

**Issue by hgiasac** [googleapis/nodejs-logging#472]
Currently `requestUrl` request data in middleware is using `req.url` variable. In express, `req.url` only returns sub-route. 

```javascript
const router = express.Router();
router.get('/', (req, res) => { ... })

app.use('/users', router);
```

![Console Log](https://i.imgur.com/iAhpsfP.png)

There are many cases that we use nested routes in express for modularization. It is better to use `req.originalUrl` for getting full path.

https://expressjs.com/en/api.html#req.originalUrl

I am ready to make PR. However, I need to verify that this feature can be doable or not.

Thanks

**Comment by bcoe** [comment]
@ofrobots can speak to this a bit better than me, but sounds like a worthwhile patch.

**Comment by ofrobots** [comment]
@hgiasac :+1:. Looking forward to the PR!
