### ISSUE TITLE
Unable to flush; exceeding quota

### ISSUE THREAD

**Issue by skjolber** [googleapis/nodejs-logging#518]
#### Environment details

  - OS: Linux
  - Node.js version: 10.16
  - npm version: 6.9.0
  - `@google-cloud/logging` version:^5.1.0

#### Steps to reproduce

  1. Do async logging
  2. Observe no async callback messages untill app is closed

So if you're writing a lot of logs, and want to space them out in time to avoid exceeding the quota, it is not clear how to do this. A search for 'flush' in the repo returns empty.

```
ERROR: { Error: Bandwidth exhausted
    at Http2CallStream.call.on (/x/node_modules/@grpc/grpc-js/build/src/client.js:101:45)
    at Http2CallStream.emit (events.js:203:15)
    at process.nextTick (/x/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 8,
  details: 'Bandwidth exhausted',
  metadata: Metadata { options: undefined, internalRepr: Map {} },
  note:
   'Exception occurred in retry method that was not classified as transient' }

```

**Comment by stephenplusplus** [comment]
I believe this is a feature request for us to implement a way to buffer messages internally until we periodically flush them. @callmehiphop does PubSub have a similar mechanism we could extract, or in general, if you learned any gotchas or pitfalls while implementing?

**Comment by callmehiphop** [comment]
The bulk of the batching logic lives [here](https://github.com/googleapis/nodejs-pubsub/blob/master/src/message-queues.ts).

**Comment by skjolber** [comment]
The issue is that when I got a batch job which requires logging a lot of values, I am unable to prevent the library from dumping them all at once; exceeding the usage quota. 

I would like to flush periodically, manually, so I can stay within the quota.

**Comment by adamstickley** [comment]
@skjolber Did you ever get a solution for this? Running into an almost identical issue but with Pub/Sub.

**Comment by bcoe** [comment]
@alexander-fenster I know we make an effort to batch together writes at the `gax` layer, any thoughts on this issue?

**Comment by alexander-fenster** [comment]
Batching of similar requests is enabled for this library. Requests are batched based on `(log_name, resource, labels)`, so if all three are the same and requests came within 50 ms, they will be sent as one request. This is configured here: https://github.com/googleapis/googleapis/blob/676104ec38754b01a5bcdbcae2faf2be58d2f44e/google/logging/v2/logging_gapic.yaml#L438-L451

![image](https://user-images.githubusercontent.com/4015807/64370305-0c204000-cfd3-11e9-80a8-109cd9b3e74c.png)

@skjolber Do your log entries have these three fields identical when you log?

**Comment by stephenplusplus** [comment]
Let's come back to this if we find out this isn't working.

@alexander-fenster Is it possible for a user to customize those values? If so, could you leave an example of how?

**Comment by alexander-fenster** [comment]
@stephenplusplus Yes, it should be possible to override these values using the constructor options. Do you want me to write a sample?  (I think I did it somewhere here before and can try to find)

**Comment by stephenplusplus** [comment]
Yeah, that would be great, just to help anyone who stops by. Sorry I missed the other sample.

**Comment by alexander-fenster** [comment]
@stephenplusplus This gist https://gist.github.com/alexander-fenster/883347a958d529c5b8a5289132b92e45 shows how to override default batching settings.
