### ISSUE TITLE
Not supporting new beta Stackdriver Kubernetes Monitoring resource format

### ISSUE THREAD

**Issue by daaain** [googleapis/nodejs-logging#525]
#### Environment details

  - OS: Debian (using `node:10.15.0` Docker image)
  - Node.js version: v10.15.0
  - npm version: 6.4.1 (using yarn 1.12.3 though)
  - `@google-cloud/logging-winston` version: 1.1.0
  - `@google-cloud/logging` version: 5.1.0

I'm using `@google-cloud/logging-winston` but I'm almost sure that the functionality / issue comes from this dependency hence opening issue here.

#### Steps to reproduce

  1. Deploy application to GKE
  2. Observe logs emitted by library only appearing under global GKE Container logs and not container logs accessed via GKE workload links

I think this is because the `resource` metadata isn't filled in with the format beta Stackdriver Kubernetes Monitoring resource expects.

This is how it looks like in log entries under GKE Container stored by the library:

```
 resource: {
  labels: {
   cluster_name: "master"    
   container_name: ""    
   instance_id: ""    
   namespace_id: "default"    
   pod_id: ""    
   project_id: "<project id>"    
   zone: ""    
  }
  type: "container"   
 }
```

And this is how it looks like in the "proper" container logs, currently stored via stdout / console output:

```
 resource: {
  labels: {
   cluster_name: "master"    
   container_name: "graphql"    
   location: "europe-west2-a"    
   namespace_name: "default"    
   pod_name: "graphql-85bf76c55c-vqstq"    
   project_id: "<project id>"    
  }
  type: "k8s_container"   
 }
```

I found this PR comment while searching: https://github.com/googleapis/nodejs-logging/pull/424#issuecomment-473608406

So I'm wondering if fixing this would be just adding one more switch case?

**Comment by daaain** [comment]
This is quite possibly a similar issue as https://github.com/googleapis/nodejs-logging/issues/125

**Comment by shahidmau** [comment]
I am also getting the same issue.

**Comment by georgianjalba** [comment]
Is there any workaround for this issue or will it be addressed anytime soon? We are currently experiencing the same issue in a kubernetes container and we have to set all labels manually which is both time consuming and not very generic in case google changes any labeling system.

**Comment by daaain** [comment]
@georgianjalba my workaround is to emit logs to the console (too) which gets picked up and labelled correctly by Stackdriver. It does the job, but kind of defeats the purpose of using the library...

**Comment by georgianjalba** [comment]
@daaain my issue is that we are using pm2 to manage the server and it seems it captures the logs and doesn't allow them to be sent to the console(too) and so using the library is the only way of going around that and sending them to stackdriver.

**Comment by EdByrnee** [comment]
> @georgianjalba my workaround is to emit logs to the console (too) which gets picked up and labelled correctly by Stackdriver. It does the job, but kind of defeats the purpose of using the library...

Hi daaain did you find any way of adding the metadata to the Stackdriver logs so that they're held under the relevant pod's logs in GKE - along with the pod's console.logs?

Thanks

**Comment by daaain** [comment]
> Hi daaain did you find any way of adding the metadata to the Stackdriver logs so that they're held under the relevant pod's logs in GKE - along with the pod's console.logs?
> 
> Thanks

Yes, but you have to use a logging library to add the metadata rather than `console.log` directly. I personally use [Winston](https://github.com/winstonjs/winston) with [Google's Logging Winston](https://github.com/googleapis/nodejs-logging-winston/).

You can of course use this library [as in the example](https://github.com/googleapis/nodejs-logging#using-the-client-library), but I find it way too verbose.

In any case console is just the log transport rather than directly used for logging.

**Comment by EdByrnee** [comment]
> > Hi daaain did you find any way of adding the metadata to the Stackdriver logs so that they're held under the relevant pod's logs in GKE - along with the pod's console.logs?
> > Thanks
> 
> Yes, but you have to use a logging library to add the metadata rather than `console.log` directly. I personally use [Winston](https://github.com/winstonjs/winston) with [Google's Logging Winston](https://github.com/googleapis/nodejs-logging-winston/).
> 
> You can of course use this library [as in the example](https://github.com/googleapis/nodejs-logging#using-the-client-library), but I find it way too verbose.
> 
> In any case console is just the log transport rather than directly used for logging.

Sorry I mean how did you add the pod_name etc. to the logging meta using winston.format() is it exposed as an environment variable or something similar?

**Comment by daaain** [comment]
> Sorry I mean how did you add the pod_name etc. to the logging meta using winston.format() is it exposed as an environment variable or something similar?

I didn't have to do anything other than using the console transport inside the GKE containers.

**Comment by EdByrnee** [comment]
> > Sorry I mean how did you add the pod_name etc. to the logging meta using winston.format() is it exposed as an environment variable or something similar?
> 
> I didn't have to do anything other than using the console transport inside the GKE containers.

HI daaain thanks for reply, so until they add metadata best solution is to have standard logging in the Container Logs and the request logging in the Global Logs?

**Comment by daaain** [comment]
> HI daaain thanks for reply, so until they add metadata best solution is to have standard logging in the Container Logs and the request logging in the Global Logs?

Yeah, you can have both transports in GKE, though I turned the Global log one off as the request bundling didn't work properly anyway in high volume scenarios, so I'm just reusing the trace id generated by the API gateway to make tracing work, as explained here: https://github.com/googleapis/nodejs-logging-winston/issues/287#issuecomment-516076018
