### ISSUE TITLE
Unexpected error determining execution environment

### ISSUE THREAD

**Issue by MeLight** [googleapis/nodejs-logging#547]
- OS: Ubuntu 18.04
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `@google-cloud/logging` version: 5.2.0

I'm getting this error:
```
/home/user/project/node_modules/@google-cloud/logging/build/src/v2/logging_service_v2_client.js:208
              throw err;
              ^
FetchError: Unexpected error determining execution environment: request to http://metadata.google.internal./computeMetadata/v1/instance failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/home/user/project/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
And this is the code:
```
# custom logger module
const {Logging} = require('@google-cloud/logging');
var logging = null;

module.exports.init = function(projectId) {
	logging = new Logging({
		projectId: projectId
	});
};

module.exports.log = function(msg, severity) {
	var syslog = logging.log("syslog");

	var resource = {
	  type: 'gce_instance',
	  labels: {
	    zone: 'global',
	    instance_id: '3'
	  }
	};

	var entry = syslog.entry(resource, {
	  "message": msg
	});

	syslog.info(entry, function(err) {});
};

# logger module usage:
var logger = require('./logger.js');

logger.log("This is a log message");

```

**It does not throw this error** every time I use the logger. In fact I'm not sure what triggers it, as the stack trace holds no clues, and I'm using the logger a lot across the app. The only thing that certainly prevents the issue from happening is if I remove the line `syslog.info(entry, function(err) {});` from the code. Then I don't get any logs but also no exceptions. 

Any pointer to where I should be looking for a solution would be very helpful.

**Comment by stephenplusplus** [comment]
Hello! Within those lines of code, the only call that actually sends an outbound request to the API is `syslog.info(...)`. And since the API requires credentials to access it, that is the first time that this library tries to sort out where those credentials are going to come from. So, to start with to try to debug this issue, I'll just explain a bit about how that process works and we can go from there.

It looks like your code doesn't provide a `keyFilename` or a `credentials` object within the constructor:

```js
logging = new Logging({
    projectId: projectId
});
```

In the absence of those properties, we look for an environment variable `GOOGLE_APPLICATION_CREDENTIALS`, that simply is a path to a service account JSON key file.

If that fails, we will check to see if you're running in an environment where you don't need any of these variables set, like in a Cloud Functions or Compute Engine environment. The way that's detected is by pinging a localhost-like metadata server that exists only on those platforms. But, that ping failed:

> Unexpected error determining execution environment: request to http://metadata.google.internal./computeMetadata/v1/instance failed

Is the stacktrace right-- are you running the code outside of a Google Cloud Compute Engine-type environment? Feel free to share any other details that could help. Thanks!

**Comment by MeLight** [comment]
@stephenplusplus thanks for the prompt reply. 
The code is running in a GCE instance. After investigating some more I have strange results which I can't make sense of at the moment. Specifically, the `log(msg)` function in my code is invoked mainly in a loop which iterates over a dataset from Datastore. On every entity processed I'm writing a log message. It seems that this error is triggered only after a certain amount of entities processed. 

For example if I run the complete loop of 373 entities that I get in the query, the logging fails with the above exception, and I see none of the logs from the set. But if I stop the loop lets say after 100 entities the exception is not thrown and I can see the the 100 lines of logs, for each entity processed. I tried to find the limit number, but it changes between restarts of the machine, so I'm not sure what to make of that. 

It feels like some sort of issue that could be solved with flushing, if that makes any sense in this context.

**Comment by stephenplusplus** [comment]
Yikes, that's interesting. Are you throttling the amount of log writes that go out at once, or do you fire them off without waiting for the previous ones to complete? If you could isolate the code that manages that flow, I can try to run it, too and we can both try to find that limit.

**Comment by MeLight** [comment]
I fire them off without waiting. Will attempt to throttle. Also, I've just reproduced with a simpler snippet:
```
const {Logging} = require('@google-cloud/logging');
const PROJECT_ID = 'my-project';
logging = new Logging({
        projectId: PROJECT_ID
});
function logMessage(msg, severity) {
        var syslog = logging.log("syslog");
        var resource = {
          type: 'gce_instance',
          labels: {
            zone: 'global',
            instance_id: '3'
          }
        };
        var entry = syslog.entry(resource, {
          "message": msg
        });
        switch(severity) {
                case "warning":
                        // module.exports.consoleLog("Logging WARNING");
                        syslog.warning(entry, function(err) {});
                        break;
                case "error":
                        // module.exports.consoleLog("Logging ERROR");
                        syslog.error(entry, function(err) {});
                        break;
                case "info":
                default:
                        // module.exports.consoleLog("Logging INFO");
                        syslog.info(entry, function(err) {});
                        break;
        }
};
let ITERS = 10000;
for(let i = 0; i < ITERS; i++) {
logMessage(`iter ${i}`);
}
```

Notice I'm trying to write 10k times. You machine might need a different number to crash. Again, it feels like there's some buffer inside that crashes it. If it is indeed the case, a flush method would be great.

Thanks

**Comment by stephenplusplus** [comment]
Related to the idea of buffering and flushing, issue #518 can track that as a feature request.

**Comment by Elyx0** [comment]
@MeLight Are you getting an `execution-id` in your stackdiver logs for these at <= 393 ?

**Comment by MeLight** [comment]
@Elyx0 hi, 

sorry I can't find those errors anymore in the stackdriver logs - either the logs expired or I got them directly from the machine logs.

**Comment by bcoe** [comment]
@MeLight are you still running into this issue? recently we added caching to the metadata lookup, and a few other improvements, in an effort to address these occasional exceptions.

**Comment by stephenplusplus** [comment]
I'll close for now, but if anyone still runs into this, please let us know.

**Comment by sghael** [comment]
I believe this issue is still happening.  I see frequent, intermittent failures in my Cloud Run endpoint.   Here is the stack trace:

```
2020-03-26 12:26:10.187 CST{ FetchError: network timeout at: http://metadata.google.internal./computeMetadata/v1/instance
2020-03-26 12:26:10.187 CST at Timeout.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1448:13)
2020-03-26 12:26:10.187 CST at ontimeout (timers.js:436:11)
2020-03-26 12:26:10.187 CST at tryOnTimeout (timers.js:300:5)
2020-03-26 12:26:10.187 CST at listOnTimeout (timers.js:263:5)
2020-03-26 12:26:10.187 CST at Timer.processTimers (timers.js:223:10)
2020-03-26 12:26:10.187 CST message:
2020-03-26 12:26:10.187 CST 'network timeout at: http://metadata.google.internal./computeMetadata/v1/instance',
2020-03-26 12:26:10.187 CST type: 'request-timeout',
2020-03-26 12:26:10.187 CST config:
2020-03-26 12:26:10.187 CST { url:
2020-03-26 12:26:10.187 CST 'http://metadata.google.internal./computeMetadata/v1/instance',
2020-03-26 12:26:10.187 CST headers: { 'Metadata-Flavor': 'Google' },
2020-03-26 12:26:10.187 CST retryConfig:
2020-03-26 12:26:10.187 CST { noResponseRetries: 0,
2020-03-26 12:26:10.187 CST currentRetryAttempt: 0,
2020-03-26 12:26:10.187 CST retry: 3,
2020-03-26 12:26:10.187 CST retryDelay: 100,
2020-03-26 12:26:10.187 CST httpMethodsToRetry: [Array],
2020-03-26 12:26:10.187 CST statusCodesToRetry: [Array] },
2020-03-26 12:26:10.187 CST responseType: 'text',
2020-03-26 12:26:10.187 CST timeout: 3000,
2020-03-26 12:26:10.187 CST params: [Object: null prototype] {},
2020-03-26 12:26:10.187 CST paramsSerializer: [Function: paramsSerializer],
2020-03-26 12:26:10.187 CST validateStatus: [Function: validateStatus],
2020-03-26 12:26:10.187 CST method: 'GET' } }```

This is the log error events for this:
![Screen Shot 2020-03-26 at 2 43 44 PM](https://user-images.githubusercontent.com/110965/77684607-94b2fd80-6f70-11ea-9c25-5572d07362a7.png)

I'm only showing the last few days, but this has been going on for weeks.
