### ISSUE TITLE
Cannot use module in Ionic4 + Angular8 + Firebase apps

### ISSUE THREAD

**Issue by merkledag** [googleapis/nodejs-logging#566]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 11.10.0
  - npm version: 6.7.0
  - `@google-cloud/logging` version: 5.2.2
  - AngularCLI: 8.2.3
 - typescript: 3.5.3
 - webpack 4.39.2
#### Steps to reproduce
Objective use nodejs-logging in an Ionic4+Angular8+Firebase app to write logs to StackDriver
In the app root:
  1. npm install @google-cloud/logging
  2. Go to @google-cloud/logging/build/proto/logging.d.ts, and add this import statement
      import {Long} from "protobufjs";
  3. Do the same in @google-cloud/logging/build/proto/logging.config.d.ts
  4. Build the Ionic app

Get a list of Module not found errors for various node core modules such as crypto, child_process, fs, zlib, http, tls, os etc. e.g.

ERROR in ./node_modules/google-gax/build/src/operationsClientBrowser.js
Module not found: Error: Can't resolve './operations_client_config' in '/home/pam/strata1/strata_forms_app/node_modules/google-gax/build/src'
ERROR in ./node_modules/@google-cloud/common/node_modules/google-auth-library/build/src/auth/googleauth.js

Does this mean that @google-cloud/logging cannot be used in Angular-Firebase apps?

Thanks!

**Comment by Yahya-khodr** [comment]
Hi @alexander-fenster 
Is this issue still under development ?
or it is already done and resolved ?
can we now use the cloud logging in Angular + firebase app ?

**Comment by alexander-fenster** [comment]
Hi @Yahya-khodr,

We don't officially support any kind of browser use case.

Having that said, the library should work with `webpack` v4 (not v5) if you follow the tweaks we do in our `webpack.config.js` and then authenticate as described in https://github.com/googleapis/google-cloud-node/issues/2933#issuecomment-547657659. Just as I said - should work, but not yet production ready, and might require some time to setup.
