### ISSUE TITLE
angular universal monitoring

### ISSUE THREAD

**Issue by mac2000** [googleapis/nodejs-logging#58]
What we are trying to do is to run Angular universal app inside GKE and collect logs to StackDriver

#### Steps to reproduce

```
npm i -g @angular/cli
ng new acme -st -sg
cd acme
ng generate universal ssr
```

[angular 5.1 universal](https://blog.angular.io/angular-5-1-more-now-available-27d372f5eb4e#fca7)

After reproducing all steps we got working universal app, but after trying add logging to it (no matter is it bunyon or winson we always get same error while trying to build app, complayinging:

```
ERROR in ./node_modules/@google-cloud/logging/src/v2/config_service_v2_client.js
Module not found: Error: Can't resolve './config_service_v2_client_config' in '/Users/mac/dev/mobjs/node_modules/@google-cloud/logging/src/v2'
 @ ./node_modules/@google-cloud/logging/src/v2/config_service_v2_client.js 17:20-64
 @ ./node_modules/@google-cloud/logging/src/v2/index.js
 @ ./node_modules/@google-cloud/logging/src/index.js
 @ ./node_modules/@google-cloud/logging-bunyan/src/index.js
 @ ./server.ts
```

problem seems to be related with webpack, I bed that if I will try to create nodejs app everything will work out of the box

if you will have problems with reproducing thing thing - please let me know I will create demo repo for this

**Comment by stephenplusplus** [comment]
We have a similar issue opened in our common issue tracker for all of the `@google-cloud/*` APIs: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/531

Currently, we don't have explicit support for using our libraries outside of a strictly Node environment.

**Comment by mac2000** [comment]
@stephenplusplus seems that you got it wrong, we are speaking about nodejs express app running inside docker container in google cloud kubernetes

**Comment by stephenplusplus** [comment]
Sorry, I definitely don't want to prematurely close, so let me re-open to make sure I understand. This line is throwing me:

> problem seems to be related with webpack, I bed that if I will try to create nodejs app everything will work out of the box

Could you make that demo repo you mentioned?

**Comment by mac2000** [comment]
Its ok do not worry about it, here is repository with demo: https://github.com/mac2000/logging58

First ensure app is working at all by:

```
git clone https://github.com/mac2000/logging58
cd logging58
npm i
npm start
```

then you should be able to see default angular app running on [localhost:4000](http://localhost:4000)

now in [server.ts](https://github.com/mac2000/logging58/blob/master/server.ts) try to uncomment lines [14-40](https://github.com/mac2000/logging58/blob/master/server.ts#L14-L40)

and run `npm run webpack:server` to reproduce issue, you gonna see bazillion of warnings and errors like mentioned above

Hope that helps

**Comment by stephenplusplus** [comment]
Thank you for putting that together. Unfortunately, since the problem is with mixing our Cloud client libraries with Webpack, that qualifies as an "out of our current bounds" implementation. Webpack is designed to take Node modules and conform them to the browser's environment.

[This issue](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/531) is still the correct place to track support for this. There has also been some discussion on this issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1821.

Sorry that we can't be much more help for now.

**Comment by smonusbonus** [comment]
Same issue here using webpack. 

```ERROR in ./node_modules/@google-cloud/logging/src/v2/config_service_v2_client.js
    Module not found: Error: Can't resolve './config_service_v2_client_config' in [...]

I don't think it's fair to disregard this saying webpack is only for browser-focused apps. I'm using typescript to build a node backend and there is no way to run this natively.
