### ISSUE TITLE
logging stops after a few hours with "retry total timeout exceeded"

### ISSUE THREAD

**Issue by gae123** [googleapis/nodejs-logging#596]
(This is in continuation of #586)

Because of #586  we yanked out the google winston log library and used directly `"@google-cloud/logging": "5.3.1",`

24 hours went by with no memory leak BUT I just realized that logging did stop about 15 hours after it started. Every attempt to write an entry since then produced the following (thousands of such messages in the log, the one below is the first). 

These messages start appearing about 7 hours after the deployment but between the 7th and the 15ht hour I do see some of our log messages as well as the "ERROR: " messages.

![image](https://user-images.githubusercontent.com/6157123/66250490-17f94200-e6f8-11e9-8a65-c832844ea962.png)

The message is written using a console.log() in the error path of the promise. Here is the approximate code that produces this message:

```ts
import * as googleLogging from '@google-cloud/logging';
...
const metadata =
        {
            resource: {
                type: "gke_container",
            }
        }
const logger = new googleLogging.Logging().log(
                "name",
            {
                removeCircular: true
            }
        );
const entry = this.logger.entry(metadata, data);
let promise = this.logger.debug(entry);  // this worked fine for several hours
promise.catch(err => {
          // This is what we see after
           console.log(`ERROR: ${util.inspect(err)}`) ;
});
```

**Comment by gae123** [comment]
Some more input. Here is the memory footprint of this GKE cluster:

![image](https://user-images.githubusercontent.com/6157123/66251166-e4bbb080-e701-11e9-8343-f8323d0f64a2.png)

The cluster starts at around 10PM, and the first ERROR: message in the logs appears at 5:05AM, exactly when you see that very fist increase in the memory usage!!

**Comment by gae123** [comment]
The cluster has three pod, what I see happening is that the issue starts in one pod, that pod keeps sending "ERROR:" while the other pods continue working find, eventually all three of them start sending only "ERROR:"

This is really serious, it prevents other issues from being diagnosed.

Why do the console.log() messages continue working?

**Comment by gae123** [comment]
As another data point, we removed completely google-logging from our code base and we now just use console.log() (for info, debug, waring) and console.error() (for error)

The problem is not happening any more after 24 hours of observation.

Although this is not the desirable solution for a number of reasons:
- no differentiation between warning, debug messages etc
- the whole payload is printed as a string in message
- etc

it is a workaround for now...

environment: 
- GKE: 1.14.3-gke.11 
- nodejs: FROM node:10.14-alpine

**Comment by bcoe** [comment]
@alexander-fenster, in our meeting today you mentioned that this potentially relates to some ongoing issues with `grpc-js`.

**Comment by gae123** [comment]
Any update on this one? Thanks!!

**Comment by bcoe** [comment]
@gae123 could you please try:

https://www.npmjs.com/package/@google-cloud/logging/v/5.4.1

and let us know if this version is continuing to have problems?

**Comment by gae123** [comment]
With 5.4.1, the system has now run for about 36 hours with no issue, we had never gone past 24 hours before so this is definitely helping!!

**Comment by bcoe** [comment]
@gae123 that's great news, I'm going to keep this open for the time being, because I expect we'll have one or two more patches for grpc-js in the near future. But, it's good to know that some of the more critical issues are being addressed.

**Comment by bcoe** [comment]
@gae123 please feel free to reopen this if you bump into this issue again, I think the issues with `@grpc/grpc-js` we're currently working on are unrelated to this bug :+1:
