### ISSUE TITLE
Logging stops after gax timeout

### ISSUE THREAD

**Issue by ralphkocher** [googleapis/nodejs-logging#617]
#### Environment details
-
  - OS: Alpine latest: 3.9.4
  - Node.js version: 12.12.0
  - `@google-cloud/logging-winston` version: 2.1.0

#### Steps to reproduce

After using latest nodejs-logging-winston in 2.1.0 the logging to Stackdriver stops suddenly after a few hours of logging. A few minutes before it stops we see the following exception trace coming from google-gax:

`Error: Retry total timeout exceeded before any response was received
    at repeat (/app/node_modules/google-gax/build/src/normalCalls/retries.js:80:31)
    at Timeout._onTimeout (/app/node_modules/google-gax/build/src/normalCalls/retries.js:113:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)`

After switching back to nodejs-logging-winston version 2.0.1 everything worked fine again. The google-gax message does not appear in 2.0.1 but immediately  comes back if we switch forward to version 2.1.0

Any ideas?

**Comment by bcoe** [comment]
@ralphkocher could I bother you to provide an `npm ls`, for a project with the same `package-lock.json` as you are deploying?

I'm specifically interested in what version of `@grpc/grpc-js` you are running, there was a variety of bug-fixes in `@grpc/grpc-js@0.6.9`.

**Comment by twskj** [comment]
I'm having the same issue.
My grpc version is
```json
"@grpc/grpc-js": {
      "version": "0.5.4",
      "resolved": "https://registry.npmjs.org/@grpc/grpc-js/-/grpc-js-0.5.4.tgz",
      "integrity": "sha512-aY4fTCz7jq7oKFmfAeZVqGzMCR5I9NLdY9E2fJ70QtGXwlJnTaN6cnbRmCk23/aKPx9UHqOtk2lyjpN6LbAaxw==",
      "requires": {
        "semver": "^6.2.0"
      }
```

**Comment by bcoe** [comment]
@twskj sounds good :+1: `5.5.3` should force you on to `@grpc/grpc-js@0.6.9`, if you continue to run into any issues, we can try running your deployment with:

GRPC_TRACE=all and GRPC_VERBOSITY=DEBUG

And I can loop someone in from `grpc` to dig into your problem specifically.

**Comment by bcoe** [comment]
@ralphkocher are you continuing to bump into these issues on `5.5.3`? If so, we can try running your deployment with debug enabled.

**Comment by twskj** [comment]
Updating to v5.5.3 does it for me.
It's been a little over 24 hours, no timeout so far

**Comment by ralphkocher** [comment]
@bcoe I run into the issue by using @google-cloud/logging-winston. They just released 3.0.0 four days ago. We will test their latest release coming days...

**Comment by bcoe** [comment]
@twskj that's great to hear, so far it's seeming like `@grpc/grpc-js@0.6.9` has squashed a variety of bugs we had related to timeouts.

@ralphkocher, when you have a chance to upgrade, you can run `npm ls` in your project; ensure that nothing in your dependency graph is on an older version of `@grpc/grpc-js`.

**Comment by soldair** [comment]
closing issue because the fix is in grpc-js. please reopen if i'm incorrect here
