### ISSUE TITLE
adding 'orderBy' field to 'getEntries()' call results in zero entries being returned

### ISSUE THREAD

**Issue by npomfret** [googleapis/nodejs-logging#630]
I am querying stack driver using the code below.  The resulting query looks like:

```
resource.type="cloud_function"
resource.labels.function_name="handleClientOrder"
d0b5fb63-0214-11ea-8de1-0242ac110004
```

(If I paste this query into the stackdriver web ui it returns lots of results)

If I add `orderBy: 'timestamp'` to the options this query returns zero results.  If I remove it I get non-zero results.

    const logging = new Logging();
    const log = logging.log(`projects/${PROJECT_ID}/logs/cloudfunctions.googleapis.com%2Fcloud-functions`);

    const pageSize = 3;
    const orderBy = 'timestamp';
    const filter = ['resource.type="cloud_function"', `resource.labels.function_name="${functionName}"`, queryText].join("\n");

    const [entries, request, response] = await log.getEntries({
        filter,
        pageSize,
        //orderBy <- removing this makes the query work
    });

    const items = [];

    for (let entry of entries) {
        const text = entry.data.toString();
        items.push(text)
    }

**Comment by laljikanjareeya** [comment]
Hey @npomfret Documentation/sample might mislead you.
The proper way to do `orderby` is `"timestamp asc"` or `"timestamp desc"` (default).
Please find reference for [Java](https://github.com/googleapis/java-logging/blob/f76206d6d137fec9e73ef7e93a8b77193d71166c/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/LoggingClient.java#L506) and [Python](https://github.com/googleapis/python-logging/blob/c6eb60179d674dfd5137d90d209094c9369b3581/google/cloud/logging/__init__.py#L25) Client.
I will create PR shorty about documentation and samples.
