### ISSUE TITLE
Error on package load

### ISSUE THREAD

**Issue by Dane456** [googleapis/nodejs-logging#655]
I'm getting a "TypeError: The "original" argument must be of type Function" error when importing the package.

#### Environment details

  - OS: macOS 10.13
  - Node.js version: 10.13
  - npm version:
  - `@google-cloud/logging` version: latest

#### Steps to reproduce

1. Load code sandbox  - https://codesandbox.io/s/z22o8qnkr4?fontsize=14&hidenavigation=1&theme=dark

2. Notice bug on app load. 

3. Comment out import Logging statement on line 11 in `pages/index.js` in code sandbox. Notice normal functioning

#### Note
CodeSandbox error is different from the error pasted here, but hopefully should still demonstrate the issue. 

Another way to repro is to use `npx create-react-app my-app` and copy and install and import the package as done in `pages/index.js` Line 11

**Comment by Dane456** [comment]
Here's [the image](https://imgur.com/a/zwT2VBT) in my local repo

**Comment by bcoe** [comment]
@Dane456 `@google-cloud/logging` does not work in the context of a web-packed application by default. I believe what is happening to you here, is that `readFile` does not exist in the browser, so the step that attempts to WebPack it fails.

There's a [thread here](https://github.com/googleapis/google-cloud-node/issues/2933) that details how one can potentially get our client libraries running in a frontend context.

A better approach, depending on your use case though, might be to use our library for your backend server, and to hit your own API endpoints from the frontend application/.

**Comment by Dane456** [comment]
@bcoe Makes sense. Thank you!!
