### ISSUE TITLE
error when using api behind a proxy :http://metadata.google.internal/computeMetadata/v1/instance/

### ISSUE THREAD

**Issue by jeromeSH26** [googleapis/nodejs-logging#658]
**_"@google-cloud/logging": "^6.0.0",
Windows 10
Node 12.12.0
typeScript 3.7.2_**

Hi guys,

I'm having an issue when using the API from my backend behind a proxy.
The error is **request to http://metadata.google.internal./computeMetadata/v1/instance failed, reason: socket hang up**

running the same code from my home network without proxy, there is no issue at all. Logging to stackdriver is running well..
I asked my network team to investigate on which port is blocked , but can no find any information.

Do you guys have any idea how to deeper investigate, or if there are some additionnal settings when running the API behind a business proxy? 
The url is quite weird and we can not track it, nor resolve it (DNS failed to find the url domain)
Below is the code I'm running. Error occurs when executing the final step `await logSection.write(logEntry);`

thks

```

const logCredendials: LoggingOptions = {
	projectId: this._projectId,
	credentials: {
		client_email: this._credentielClientEmail,
		private_key: this._credentialPrivateKey,
	 },
};
const loggingClient: Logging = new Logging(logCredendials);
const logSection: Log = loggingClient.log(this._logSection);
const resource = {
	type: "project",
	labels: {projectId: this._projectId,},
};
arrlogData.forEach(async (logData: ILogging<TLogType>) => {
	const logEntry: Entry = logSection.entry(
		{
                        resource,
			severity: (logData.severity as unknown) as string,
		},
		logData
        );
        try {
	     await logSection.write(logEntry); <--Error occurs here
        } catch (error) {
	     console.log(`error writting ${logEntry} - ${error.message}`);
       }
});
return true;
```

**Comment by bcoe** [comment]
👋 as of right now, I don't believe http proxies work with `@grpc/grpc-js` (@murgatroid99 I'm correct that this isn't yet implemented?).

One option would be to install the [grpc dependency](https://www.npmjs.com/package/grpc), and to write your code something like this:

```js
const logCredendials: LoggingOptions = {
	projectId: this._projectId,
	credentials: {
		client_email: this._credentielClientEmail,
		private_key: this._credentialPrivateKey,
	 },
         grpc: require('grpc')
};
const loggingClient: Logging = new Logging(logCredendials);
```

Make sure you've set `HTTP_PROXY` and `HTTPS_PROXY` environment variables, after having done so.

**Comment by jeromeSH26** [comment]
ok will try it
HTTP_PROXY and HTTPS_PROXY environment variables are set in nmp, yarn and also when running the program:
`set https_proxy=http://****:8080 && set NODE_OPTIONS=--max-old-space-size=4096 && ts-node-dev --respawn src/index.ts"`

**Comment by stephenplusplus** [comment]
I have sent a PR to hopefully address the last issue, regarding `options.grpc` not being allowed: #676

**Comment by jeromeSH26** [comment]
The error to access stackdriver behind a proxy happens again, although there is no issues with proxy.

I'm quite confused on the nextwork configuration on GCP about stackdrivers ports,...

Where this information could be found ? Everything is working well for a couple of months, and all of a sudden, impossible to log to stackdriver, without changing any code or credentials. So the issue might be related to network, but documentation on that topic is quite poor..

Rgds

**Comment by murgatroid99** [comment]
The statement above is correct. Currently `@grpc/grpc-js` has no support/handling for proxies.

**Comment by pdanysz** [comment]
Hi,

I have the same problem.
Any idea when it will be solved ? or planned to be add to support proxies?

Thx

**Comment by losalex** [comment]
@murgatroid99,
Reaching out to see if proxy support was added to `@grpc/grpc-js ` or not - can you please confirm?
Thanks!

**Comment by murgatroid99** [comment]
Yes, `@grpc/grpc-js` supports proxies now. The environment variables that control that feature are documented [here](https://github.com/grpc/grpc-node/blob/master/doc/environment_variables.md).

**Comment by bcoe** [comment]
Going ahead and closing this, as this issue is from before proxies were supported by gRPC.

@losalex let us know in a new issue if you have any trouble following @murgatroid99's documentation.
