### ISSUE TITLE
stoped working yesterday from kubernetes engine

### ISSUE THREAD

**Issue by nabulaer** [googleapis/nodejs-logging#68]
#### Environment details

  - OS: linux
  - Node.js version: 6.10.3
  - npm version:
  - @google-cloud/logging version: 1.1.2 , 1.1.3

#### Steps to reproduce

 running the sample code from google docs. on local dev it works. on K8 it stopped yesterday. it did work until now. when I connect to the pod and run the code , the promise that return from log.write() is never resolved. no errors are going to the logs on gcp console. the stdout is going to the logs from nodejs. so the pod has access but not from the nodejs module

since promise is not resolved memory is growing all the time. 

Thanks!

**Comment by nabulaer** [comment]
I did not think it is related to issue #53 since it worked for me on 1.1.2 for the past weeks. but I have tried reverting to 1.1.1 and now logging works. so maybe it is related.

**Comment by nmathon** [comment]
+1
Hi can reproduce exactly the same problem. It's working with 1.1.1 but not with 1.1.2

**Comment by stephenplusplus** [comment]
I've been able to reproduce, and I'm taking a look at it. Sorry for the delay.

**Comment by stephenplusplus** [comment]
I believe the fix has just been released under 1.1.5. Please try it out and let me know how it goes!

**Comment by nabulaer** [comment]
tested with version 1.1.7 so far it is working.
