### ISSUE TITLE
"Illegal instruction" on ARMv6

### ISSUE THREAD

**Issue by Murillhou** [googleapis/nodejs-logging#69]
#### Environment details

  - OS: Raspbian 9 GNU/Linux armv61
  - Node.js version: 9.4.0
  - npm version: 5.6.0
  - @google-cloud/logging version: 1.1.3

#### Steps to reproduce

  1. Run npm install @google-cloud/logging in fresh project on a Raspberry Pi zero W (armv6).
  2. Run the example code using my own project name and credentials (tested with different ones).
  3. The terminal outputs "Illegal instruction".

Maybe some error on architecture detection during the installation led to some of the code being compiled for armv7 or others...

Thanks!

**Comment by stephenplusplus** [comment]
Hey @Murillhou, thanks for reporting. These issues are tricky-- can you see this other issue in case it offers any help? https://github.com/googleapis/nodejs-speech/issues/12

cc @alexander-fenster

**Comment by Murillhou** [comment]
Thank you very much @stephenplusplus !

This is solved by rebuilding grpc library using the command `npm rebuild --build-from-source grpc` as stated here https://github.com/googleapis/nodejs-speech/issues/12 and here https://github.com/grpc/grpc/issues/13258.
