### ISSUE TITLE
Errors are not automatically pushed to Error Reporting

### ISSUE THREAD

**Issue by jankrynauw** [googleapis/nodejs-logging#705]
#### Environment details

  - OS: MacOS
  - Node.js version: 10.15.3
  - npm version: 6.13.7
  - `@google-cloud/logging-winston` version: 3.0.5
  - `winston` version: 3.2.1

#### Using @google-cloud/logging-winston

I would like to send all logs to Google Logging, as well as errors to Error Reporting.  The following is directly from the docs:
```
const winston = require('winston');

// Imports the Google Cloud client library for Winston
const {LoggingWinston} = require('@google-cloud/logging-winston');

const loggingWinston = new LoggingWinston({
    serviceContext: {
        service: 'my-service', // required to report logged errors to the Google Cloud Error Reporting console
        version: 'my-version'
    }
});

// Create a Winston logger that streams to Stackdriver Logging
// Logs will be written to: "projects/YOUR_PROJECT_ID/logs/winston_log"
const logger = winston.createLogger({
    level: 'info',
    transports: [
        new winston.transports.Console(),
        // Add Stackdriver Logging
        loggingWinston,
    ],
});

// Writes some log entries
logger.error('warp nacelles offline');
logger.info('shields at 99%');
```

As expected, logs are pulled through to Google Logging:

![logging](https://user-images.githubusercontent.com/18016598/74224521-ae9ac880-4cc1-11ea-9ba1-9559265832e8.png)

No errors are however pushed into Google Error Reporting:

![error_reporting](https://user-images.githubusercontent.com/18016598/74224765-1cdf8b00-4cc2-11ea-9796-61781556541a.png)

#### Using @google-cloud/error-reporting works as expected

I tested using the @google-cloud/error-reporting library directly and all works as expected:

```
process.env.NODE_ENV = 'production';
// Imports the Google Cloud client library
const {ErrorReporting} = require('@google-cloud/error-reporting');
// Instantiates a client
const errors = new ErrorReporting({
    serviceContext: {
        service: 'Service1',
        version: 'Version1'
    }
});
// Reports a simple error
errors.report('An error reported using @google-cloud/error-reporting');

```

![error_reporting_direct](https://user-images.githubusercontent.com/18016598/74225696-dd19a300-4cc3-11ea-8383-900c18028024.png)

**Comment by JustinBeckwith** [comment]
@stephenplusplus I think this one is going to take a little digging

**Comment by Elyx0** [comment]
Don't you need to write to a log containing `err` ?
```
  // This is the name of the StackDriver log stream that will receive the log
  // entry. This name can be any valid log stream name, but must contain "err"
  // in order for the error to be picked up by StackDriver Error Reporting.
```

**Comment by stephenplusplus** [comment]
Found on https://cloud.google.com/nodejs/docs/reference/logging-winston/0.11.x#error-reporting:

> Any `Error` objects you log at severity `error` or higher can automatically be picked up by Stackdriver Error Reporting

So, I think this will be a simple fix:

```diff
- logger.error('warp nacelles offline');
+ logger.error(new Error('warp nacelles offline'));
```

Let me know if you still have any issues!
