### ISSUE TITLE
Missing Credentials Object in API

### ISSUE THREAD

**Issue by sbutalia** [googleapis/nodejs-logging#710]
const loggingWinston = new LoggingWinston(gkey); doesn't seem to accept a credentials object.

This is a common format in other @google-cloud libraries.
Example:
https://github.com/googleapis/nodejs-bigquery/blob/master/src/bigquery.ts#L195-L197

**Comment by stephenplusplus** [comment]
Make sure the credentials are provided like:

    new LoggingWinston({ credentials: {private_key: ...} })

**Comment by sbutalia** [comment]
Got it. Thank you! :)
