### ISSUE TITLE
Dry run support in Write API

### ISSUE THREAD

**Issue by Achuth17** [googleapis/nodejs-logging#711]
I am trying to set dryRun flag of the [write api](https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write). 

The `WriteOptions` interface does not support passing the dryRun boolean. Is there any other way to accomplish this?

**Comment by stephenplusplus** [comment]
Looks like an oversight. I'll try to PR that real quick. Thanks for catching it!
