### ISSUE TITLE
jsdoc generated html missing for overloaded methods

### ISSUE THREAD

**Issue by zamnuts** [googleapis/nodejs-logging#723]
#### Environment details

  - OS: all
  - Node.js version: all
  - npm version: 
  - `@google-cloud/logging` version: 7.2.2
  - `jsdoc` version: 3.6.3

#### Steps to reproduce

  1. npm run docs
  2. view docs/index.html in browser
  3. notice many methods are missing from `Log` and other classes

Example code snippet: https://github.com/googleapis/nodejs-logging/blob/56a8ed84ab5d9bad137e8b5ac779a2f1e24aed6a/src/log.ts#L737-L819

See TypeScript issues:
- https://github.com/microsoft/TypeScript/issues/3294
- https://github.com/microsoft/TypeScript/issues/407

A workaround is to move the jsdoc comment adjacent to the concrete method, and after the overload signatures.

**Comment by laljikanjareeya** [comment]
@zamnuts Thanks for catching it!
