### ISSUE TITLE
support bundle request in API layer

### ISSUE THREAD

**Issue by xiaozhenliu-gg5** [googleapis/nodejs-logging#748]
Today we support bundling request from micro-generator. Eventually we might want to move this logic to manual layers, and drop it from the generator.

**Comment by losalex** [comment]
@xiaozhenliu-gg5 , thanks for filing this issue and apologies for long time to respond. Can I ask you please provide more details on your request? Would it be possible for you to include also some links?

**Comment by losalex** [comment]
Closing this issue due to staleness and lack of response - feel free to reactivate or comment.
