### ISSUE TITLE
structured log data with "null" values being dropped in response from API

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-logging#818]
Without corresponding code changes, we're suddenly seeing `null` values in structured responses from the logging API being dropped.

We should root cause this.

see: https://github.com/googleapis/nodejs-logging/pull/817

**Comment by stephenplusplus** [comment]
Do you know the commit / change when this stopped working?

**Comment by stephenplusplus** [comment]
Just adding a note that I've confirmed the data is saved upstream, and the REST API returns the value. I've also confirmed we don't receive these values from the generated API's response-- if the value is null, it's just not there.

**Comment by bcoe** [comment]
@stephenplusplus thanks for confirming, this seems like something we should probably escalate to @alexander-fenster's team.

**Comment by stephenplusplus** [comment]
@bcoe @alexander-fenster any chance this is being tracked somewhere else we can tune into?
