### ISSUE TITLE
stackdriver logs are not written when using with node js v10.20.1 in cloud functions of gcp

### ISSUE THREAD

**Issue by Gajananlohar** [googleapis/nodejs-logging#819]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-logging/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Windows 10 pro
  - Node.js version: 10.20.1
  - npm version: 6.14.5
  - `@google-cloud/logging` version: 7.3.0

#### Steps to reproduce

  1. Use the below code:
`'use strict';
const {Logging} = require('@google-cloud/logging');

exports.testlogging = async (req, res) => {
    await quickstart()
    res.send({msg:"hello world!"})
};

async function quickstart(
    logName = 'my-log' // The name of the log to write to
  ) {
    // Creates a client
    const logging = new Logging();
  
    // Selects the log to write to
    const log = logging.log(logName);
  
    // The data to write to the log
    const text = 'Hello, world!';
  
    // The metadata associated with the entry
    // const metadata = ;
  
    // Prepares a log entry
    const entry = log.entry({
        resource: {type: 'global'},
        severity: "info",
      }, text);
  
    async function writeLog() {
      // Writes the log entry
      await log.info(entry);
      console.log(`Logged: ${text}`);
    }
    await writeLog();
  }
`

  2. deploy in the code using google cloud functions command: `gcloud functions deploy testlogging --runtime nodejs10 --trigger-http`

 3. now access the url and verify that the no logs are written in stackdriver log of the function.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment]
@Gajananlohar just to confirm, when you're checking the logs on `cloud.google.com`, are you selecting the `global` option when viewing?

**Comment by stephenplusplus** [comment]
@Gajananlohar since we haven't heard back, I'm going to close in the hopeful assumption that @bcoe's suggestion did the trick! If that's wrong, however, just let us know and we'll re-open and re-investigate. Thanks!
