### ISSUE TITLE
Multiple resource-exhaustion-related errors after an update to v8.0.0

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-logging#835]
#### Environment details

  - OS: Container Optimized OS (cos-stable-81-12871-119-0)
  - Node.js version: 14.4.0
  - npm version: 6.14.5
  - `@google-cloud/logging` version: 8.0.0

#### Steps to reproduce

I have a service running in a managed instance group that uses `@google-cloud/logging`. After a recent update of `@google-cloud/logging` from v7.3.0 to v8.0.0 I've observed that the service was running out of memory rapidly and no logs were written anymore. This was due to a log queue building up in memory and not being forwarded to Cloud Logging. I've observed many errors related to bandwidth exhaustion, as well as seeing per minute log write quota being reached. Sample errors:
- Code 8, "Quota exceeded for quota metric 'Log ingestion requests' and limit 'Log ingestion requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:XXXXXXXXXX'."
- Code 8, "Bandwidth exhausted".
- Code 13, "Received RST_STREAM with code 2"

I've reached ~8 million errors in 15 minutes.

After a downgrade to v7.3.0, all went back to normal.

**Comment by bcoe** [comment]
@alexander-fenster this sounds like something we should dig into next week. We converted the library to TypeScript between `v7.3.0` and `v8.x.x`, and a lot of dependencies were updated during this process.

@merlinnot thank you for the bug report, for now I've made it a `p2` since you have a workaround.

**Comment by bcoe** [comment]
@merlinnot would you be able to provide an example of how you are integrating with  the logging library (are you  using a wrapper like `@google-cloud/logging-winston` or `@google-cloud/logging-bunyan`?) or are you using the library directly.

If you're using the library directly, perhaps you could share some source that provides a basic outline of how you're interacting the library?

**Comment by merlinnot** [comment]
@bcoe I'm using the library directly. As far as I remember, `log.write` has/had a buffering (batching) mechanism for logs, that's what I was relying on - calling `log.write` and not awaiting it. It works with v7, doesn't work with v8.

**Comment by alexander-fenster** [comment]
@merlinnot Thank you for the report - I found a problem and I'm working on a fix.

**Comment by bcoe** [comment]
@merlinnot we've released a candidate release of the library which we believe should address your batching issues:

https://www.npmjs.com/package/@google-cloud/logging/v/8.0.4-beta.0

Let us know if it works well for you, and we'll call this issue fixed?

**Comment by bcoe** [comment]
@merlinnot we've released the latest version of the library with the batching fix, please let us know if you  continue to run into any issues.

**Comment by merlinnot** [comment]
Hey, I somehow missed your message, sorry. As a mitigation we had to start using a default COS logging agent (the one in Ruby) and there's no real reason for us to switch back, so I don't have an easy way to test that. But I believe in your skills so we can consider the issue closed :)
