### ISSUE TITLE
getLogs() returning error stating it is not a function

### ISSUE THREAD

**Issue by Lunastryke** [googleapis/nodejs-logging#841]
Following the below code in the documentation leads to a getLogs() is not a function error being thrown. I have tried getEntries(options) and it is working fine, but getLogs() doesnt seem to work

`async function listLogs() {
  // [START logging_list_logs]
  // Imports the Google Cloud client library
  const { Logging } = require('@google-cloud/logging');

  // Creates a client
  const logging = new Logging();

  async function printLogNames() {
    const [logs] = await logging.getLogs();
    console.log('Logs:');
    logs.forEach((log) => {
      console.log(log.name);
    });
  }
  printLogNames();
  // [END logging_list_logs]
}
`

**Comment by stephenplusplus** [comment]
That is very interesting, as the method definitely exists! Can you show the exact code you're running, following this template?

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/logging` version:

#### Steps to reproduce

  1. ?
  2. ?

**Comment by Lunastryke** [comment]
Hi, my bad. It turns out my @google-cloud/logging version was version 2.0.0. Upon updating to the latest release it works fine. Thanks for the help
