### ISSUE TITLE
npm audit high severity vulnerability

### ISSUE THREAD

**Issue by johnjacobkenny** [googleapis/nodejs-logging#904]
The fix may be in a dependency, but capturing this issue here since an update is required for this library.

![image](https://user-images.githubusercontent.com/19240564/95218934-6dd45e80-0812-11eb-9be1-868f8e3f1b01.png)

1) Is this a client library issue or a product issue?
Client library issue

2) Did someone already solve this?
No.

3) Do you have a support contract?
No.

#### Environment details

  - OS: NA
  - Node.js version: NA
  - npm version: NA
  - `@google-cloud/logging` version: 8.0.6

#### Steps to reproduce

  1. Run `npm audit`

**Comment by stephenplusplus** [comment]
It's out! 8.0.8

**Comment by johnjacobkenny** [comment]
Thanks!
