### ISSUE TITLE
getEntries: Insufficient tokens for quota 'logging.googleapis.com/read_requests' and limit 'ReadRequestsPerMinutePerProject' 

### ISSUE THREAD

**Issue by xMTinkerer** [googleapis/nodejs-logging#91]
I am getting this error when ever I run the following code. 

```
Error: Insufficient tokens for quota 'logging.googleapis.com/read_requests' and limit 'ReadRequestsPerMinutePerProject' of service 'logging.googleapis.com' for consumer 'project_number:1234567890123'.
```

Apparently, this is due to the "Read Requests" Quota which I see here:
https://console.cloud.google.com/apis/api/logging.googleapis.com/quotas?project=PROJECT_ID&authuser=1&duration=PT1H

![image](https://user-images.githubusercontent.com/10202041/37368267-fc36ea1e-26c2-11e8-8599-bec6bd6e0968.png)

However, this is literally the only code that is contributing to this quota. As you can see in the image, there are 0 entries until I run this code, then it spikes to 60 per minute and I get the error above. I'm guessing there is something deeper in the `getEntries` function that makes an additional call that contributes to the "Read Requests" quota, but I can't tell what it might be. I may not be looking deep enough though. 

#### Environment details

  - OS: MacOS but also App Engine
  - Node.js version: v8.5.0
  - npm version: 5.6.0
  - @google-cloud/logging version: 1.1.4

#### Steps to reproduce
1. Copy this code into a file or the repl. Replace INSTANCE_NAME, or not. The error occurs regardless of a good instance name. 
```javascript

const Logging = require( '@google-cloud/logging' );
const logging = new Logging();


var theLogFilter = 'jsonPayload.resource.name=INSTANCE_NAME';

var metadata;

logging.getEntries({
  filter: theLogFilter
}, (err, entries, nextQuery, apiResponse) => {

	if( err ) {
		console.log( "ERROR: " + err );
		return;
	}

	console.log( "RESULTS: " + JSON.stringify( entries ) );
});

```

This results in:

```

travisdepuy@appletree:~/the-badger$ node
> 
> 
> const Logging = require( '@google-cloud/logging' );
undefined
> const logging = new Logging();
undefined
> 
> 
> var theLogFilter = 'jsonPayload.resource.name=INSTANCE_NAME';
undefined
> 
> var metadata;
undefined
> 
> logging.getEntries({
...   filter: theLogFilter
... }, (err, entries, nextQuery, apiResponse) => {
... 
... 	if( err ) {
... 		console.log( "ERROR: " + err );
... 		return;
... 	}
... 
... 	console.log( "RESULTS: " + JSON.stringify( entries ) );
... });
undefined
> 
> 
> 
> 
> 
> ERROR: Error: Insufficient tokens for quota 'logging.googleapis.com/read_requests' and limit 'ReadRequestsPerMinutePerProject' of service 'logging.googleapis.com' for consumer 'project_number:1234567890123'.

> 

```

I've tried waiting a couple of days and it still seems to happen. Does this happen for anyone else?

**Comment by stephenplusplus** [comment]
There's only one change you need to not blow the quota, and that's:

```diff
logging.getEntries({
+   autoPaginate: false,
    filter: theLogFilter
}, (err, entries, nextQuery, apiResponse) => {
```

By default, `autoPaginate` is set to true. When the API responds with a cursoring token, that indicates to us that there may be more results, so we run `nextQuery` automatically. Interestingly, this returns a cursoring token endlessly, which is why it runs until the quota limit is met.

**Comment by xMTinkerer** [comment]
Ahhh, yea, that makes sense. I failed to notice that when I put that filter into the log viewer, there was a time range constraint that isn't accounted for explicitly in the filter. So while in log viewer I was only getting 2-3 results, but likely with the `getEntries` call, I was getting LOTS of results which was causing it to use multiple pages, and thus make multiple API calls. 

I think the real answer here is that I need to rethink my filter, but thinking about the pagination was helpful! Thank you!

**Comment by xMTinkerer** [comment]
So that actually brings up a good point though, will pagination ever work? If I'm only allowed 60 calls per second, and pagination causes multiple calls per millisecond, then it seems like it would always fail without some kind of delay between pages?

**Comment by stephenplusplus** [comment]
Indeed, it seems like `getEntries` will surpass the limit with `autoPaginate: true`. I'll open a new issue for this.

**Comment by stephenplusplus** [comment]
Issue: #93
