### ISSUE TITLE
sample: improve the advanced log sample in logs.js 

### ISSUE THREAD

**Issue by nicoleczhu** [googleapis/nodejs-logging#922]
Rather than logging "hello world" show a more complex example logging a httprequest type or similar

**Comment by laljikanjareeya** [comment]
@nicoleczhu there is already [http request sample](https://github.com/googleapis/nodejs-logging/blob/master/samples/http-request.js) that demonstrate the same we can use the same.

**Comment by nicoleczhu** [comment]
Neat, thanks!
