### ISSUE TITLE
getEntries() exhausts read quota by default

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-logging#93]
It should be easy to reproduce:

```js
logging.getEntries((err, entries) {
  err.message === "RESOURCE_EXHAUSTED: Insufficient tokens for quota 'logging.googleapis.com/read_requests' and limit 'ReadRequestsPerMinutePerProject' of service 'logging.googleapis.com' for consumer 'project_number:...'"
})
```

This is because `autoPaginate: true` is enabled by default, and there are generally thousands of logs to process. Should the GAPIC / GAX layer be doing something differently to throttle these requests?

@alexander-fenster

**Comment by stephenplusplus** [comment]
Ping ping @alexander-fenster

**Comment by alexander-fenster** [comment]
Not sure if we can do anything here in GAX layer, for me it works as supposed to - is it wrong? We might want to disable `autoPaginate` by default as it probably does not make much sense here if it consumes all the quota very fast. I will ask the API team if they could have ideas here.

**Comment by stephenplusplus** [comment]
I think this is a general question that applies to any list* endpoint. `logging.getEntries()` is a good example of something that probably should be handled differently from the usual (although, that would be a breaking change now). API team input would be great.

**Comment by callmehiphop** [comment]
Hasn't been any activity here in a while, but I assume this issue still exists. @stephenplusplus have we heard much noise about this? If not, maybe we should just close this out.

**Comment by bcoe** [comment]
@alexander-fenster in our micro-generator generated libraries, will auto paginating behave in the same wa (I know I'd picked your brain about something like async generators, back when I first started). Curious if we might be able to address this problem in the not too distant future, by being less aggressive with auto-pagination in our GAPIC libraries in general (like @callmehiphop suggests).

**Comment by alexander-fenster** [comment]
@bcoe No other language does what we do here (just silently fetch all the data). I'll be happy to remove the auto-paginate-by-default behavior and make it opt-in in TypeScript. This will require semver major release for those libraries that are affected. But since I guess TypeScript will be a semver major anyway, we might be fine with it.

**Comment by bcoe** [comment]
@alexander-fenster if we document an elegant API for paginating results in, I think it's worth the breaking change to eliminate the oddball behavior of auto-paginating in all the data.

**Comment by stephenplusplus** [comment]
I'm not sure defaulting to `autoPaginate: false` would be ideal. That was the original approach in the library, and users found it surprising they had to deal with self-paginating, and then figuring out how to do it on top of that isn't a joy:

```js
const [results, secondQuery] = await storage.getBuckets()

// search the results array to determine if I need to keep paging...

if (secondQuery) {
  const [secondResults, thirdQuery] = await storage.getBuckets(secondQuery)  
}


if (thirdQuery) {
  const [secondResults, thirdQuery] = await storage.getBuckets(secondQuery)
}
```

If we had a better looking option for how that code would look, that would be helpful. However, it might still not be what the average user wants, which has historically been the user we're designing for. When a user needs to throttle API requests for cost or performance reasons, they can opt-out of autoPaginate.

Maybe we should just opt-out `getEntries()` by default, since we know that to be a large response. Documentation

**Comment by callmehiphop** [comment]
I think if we're discussing making a breaking change I'd like to shamelessly plug the idea of removing `autoPaginate` altogether and having 2 methods

- `getEntries()` - retrieves 1 page of entries
- `getAllEntries()` - retrieves all entries

**Comment by bcoe** [comment]
The plan of action is to move away from `autoPaginate` towards async iterators; but this will be towards the end of the year when we retire Node 8 in favor of Node 10.

**Comment by bcoe** [comment]
@alexander-fenster once we deprecate Node 8, it might be worth documenting async iterators in this repo, and we can close this old issue.

**Comment by keenan-devrel** [comment]
Async iterators are in.
Docs for the above are in.
Pending samples.
Closing this issue.
