### ISSUE TITLE
keyFile not working since 8.0.10

### ISSUE THREAD

**Issue by protyposis** [googleapis/nodejs-logging#947]
Steps to reproduce:

 * Download service account credentials JSON file
 * Create `Logging` instance with path to JSON: `new Logging({ keyFile: 'path/to/credentials.json' });`
 * Receive error:
   ````
   <redacted>\node_modules\google-gax\build\src\fallback.js:59
                throw new Error(JSON.stringify(options) +
                ^

   Error: {"servicePath":"logging.googleapis.com","port":443,"clientConfig":{},"fallback":true,"libName":"gccl","libVersion":"8.0.10","scopes":["https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloud-platform.read-only","https://www.googleapis.com/auth/logging.admin","https://www.googleapis.com/auth/logging.read","https://www.googleapis.com/auth/logging.write"],"keyFile":".\\gcp-logging-credentials.json"}You need to pass auth instance to use gRPC-fallback client in browser. Use OAuth2Client from google-auth-library.
    at new GrpcClient (<redacted>\node_modules\google-gax\build\src\fallback.js:59:23)
    at new ConfigServiceV2Client (<redacted>\node_modules\@google-cloud\logging\build\src\v2\config_service_v2_client.js:88:25)
    at new Logging (<redacted>\node_modules\@google-cloud\logging\build\src\index.js:126:30)
    [...]
   ```

This is happening in all versions since 8.0.10 and is working until 8.0.9. Might be related to https://github.com/googleapis/nodejs-logging/pull/935.

**Comment by stephenplusplus** [comment]
I'm not sure we ever (intentionally, anyway) meant to support `keyFile`. Instead, it's `keyFilename`. Could you give that a shot?

**Comment by protyposis** [comment]
I tried both, it's the same behavior. Seems to be an alias: https://github.com/googleapis/google-auth-library-nodejs/blob/b4d139d9ee27f886ca8cc5478615c052700fff48/src/auth/googleauth.ts#L140

**Comment by alexander-fenster** [comment]
Thanks @protyposis for the report. Seems like the new fallback detection logic did not work well for your case :( 

Can you try passing `fallback: false` to the constructor? (so it becomes `new Logging({ keyFile: 'path/to/credentials.json', fallback: false })`)  Apparently it thinks you're in browser - any chance you have a global `window` object?

**Comment by alexander-fenster** [comment]
...also, if you could provide the output of `npm ls`, it would be helpful too. Thank you!

**Comment by protyposis** [comment]
`fallback: false` works, and I indeed have `global.window` set to an empty object (seems to be a pollution from a 3rd party package).  `npm ls` output is extremely long so here's it in a gist: https://gist.github.com/protyposis/cba664e4ee10dfcbf20655f6081fd7f0

Thanks for the fast feedback!

**Comment by alexander-fenster** [comment]
Thank you! I will probably change the detection to look at `window.fetch` or something like that, more browser specific. It will never get perfect but will reduce the amount of false browser detections.
