### ISSUE TITLE
Auto-detection when used on Cloud Run (managed)

### ISSUE THREAD

**Issue by romaincointepas** [googleapis/nodejs-logging#959]
Could Cloud Run (managed) be auto-detected in https://github.com/googleapis/nodejs-logging/blob/master/src/metadata.ts#L147-L164 the same way it's already being done with Cloud Functions, Compute, etc.?

This seems to work:
```
{
  type: 'cloud_run_revision',
  labels: {
    configuration_name: process.env.K_CONFIGURATION,
    revision_name: process.env.K_REVISION,
    service_name: process.env.K_SERVICE
  }
}
```

**Comment by nicoleczhu** [comment]
Absolutely. We plan to do so for a few of the GCP platforms. Adding CloudRun to the roadmap as well.

**Comment by DustinJSilk** [comment]
Autodetection doesn't seem to be working for me in Cloud Run with these package.json settings:

```
  "resolutions": {
      "@google-cloud/logging": "^9.5.4",
  },
  "dependencies": {
      "@google-cloud/logging": "^9.5.4",
      "@google-cloud/logging-winston": "^4.1.0",
    }
```

This is my yarn.lock file
```
"@google-cloud/logging@^9.0.0", "@google-cloud/logging@^9.5.4":
  version "9.5.4"
  resolved "https://registry.yarnpkg.com/@google-cloud/logging/-/logging-9.5.4.tgz#5323a99cfb63ae07f3ce0032ff9bb314bb91cecc"
  integrity sha512-Ab3w5lD4SDksQzyDPoJZlEkELhPCGxaQfDBoNN0wdgjpcvsyswUBNyu/Bu000GyNICaHK6xvaSOWlbthDFd6kQ==
```

Adding the config mentioned in the original post solved the problem for me however.
