### ISSUE TITLE
Update logging quickstart sample

### ISSUE THREAD

**Issue by 0xSage** [googleapis/nodejs-logging#971]
Improve the Logging quickstart [in Node](https://cloud.google.com/logging/docs/samples/logging-quickstart#logging_quickstart-nodejs). Quickstart should work out of the box and contain all the instructions (in comments) so users can immediately see their logs. 

Additional criteria: 
- [ ] include comments on various [ways to authenticate](https://cloud.google.com/docs/authentication)
- [ ] encourage users to log with standard log wrappers, demonstrated in [Bunyan quickstart](https://cloud.google.com/logging/docs/samples/logging-bunyan-quickstart) or [Winston quickstart](https://cloud.google.com/logging/docs/samples/logging-winston-quickstart) rather than directly writing [LogEntries](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry). Context: In an ideal world, customers should be able to use existing logging frameworks native to their language. With some simple appender/handler to also ship logs to Cloud Logging. Customers aren't locked into logging library syntax, thus it's easier to both onboarding and offboard off of these client libraries. 
- [ ] comment that if users need more customizable logs, redirect to [writing log entries](https://cloud.google.com/logging/docs/samples/logging-write-log-entry)

**Comment by rubiagatra** [comment]
Can I help @0xSage?

**Comment by losalex** [comment]
@rubiagatra, thanks a lot for reaching out and offering help and sorry for long time it takes to resolve this issue.
Feel free to share here any specific samples/comments you think should be included in the resolution and we will try our best to incorporate those once we get to deal with this issue.

**Comment by meredithslota** [comment]
Closed in favor of https://github.com/googleapis/nodejs-logging/issues/1266 which specifies details to be fixed.
