### ISSUE TITLE
Support async iterators in handwritten layer for all "list x" calls

### ISSUE THREAD

**Issue by 0xSage** [googleapis/nodejs-logging#988]
Create functions getEntriesAsync(), getLogsAsync() and getLogMetricAsync(), extending [listlogentriesasync](https://googleapis.dev/nodejs/logging/latest/v2.LoggingServiceV2Client.html#listLogEntriesAsync), listlogsasync, listlogmetricsasync, etc

Async iterators are available in the GAPIC portion of this lib. For example: users can now do by: 
```javascript
const {Logging, LoggingServiceV2} = require('@google-cloud/logging');
const logging = new Logging();

async function getlogsAsync() {
  const time = new Date();
  time.setHours(time.getHours() - 3); // change this up
  const timeFilter = `timestamp >= "${time.toISOString()}"`;

  const req = {
    resourceNames: ["projects/log-bench"],
    filter: timeFilter,
  }

  const iterable = logging.loggingService.listLogEntriesAsync(req);
  for await (const response of iterable) {
    console.log(response);
  }
}

getlogsAsync();
```

This is clunky. Write a similar wrapper for these funcs here: https://github.com/googleapis/nodejs-logging/blob/543533a02f293028081e7d31e3a98be1677b426a/src/index.ts#L590

**Comment by losalex** [comment]
Closing this issue due to it is pretty stale and seems there is a lack of demand - feel free to reopen or comment if this feature is really required.
