### ISSUE TITLE
Extend handwritten with sink exclusion functionality

### ISSUE THREAD

**Issue by 0xSage** [googleapis/nodejs-logging#989]
Create handwritten wrappers around:
      'listExclusions',
      'getExclusion',
      'createExclusion',
      'updateExclusion',
      'deleteExclusion',

https://github.com/googleapis/nodejs-logging/blob/c9a69da3cf4ec3e87f30afc22344191a3e43e26a/protos/google/logging/v2/logging_config.proto#L488

**Comment by losalex** [comment]
Closing this issue due to it is pretty stale and seems there is a lack of demand - feel free to reopen or comment if this feature is really required.
