### ISSUE TITLE
Extend handwritten with log metrics functionality

### ISSUE THREAD

**Issue by 0xSage** [googleapis/nodejs-logging#990]
In [log metrics proto](https://github.com/googleapis/nodejs-logging/blob/master/protos/google/logging/v2/logging_metrics.proto), see `DeleteLogMetric`, `UpdateLogMetric`, `CreateLogMetric`, `ListLogMetrics` are enabled. Write a wrapper & tests to make this feature more accessible for users.

**Comment by losalex** [comment]
Closing this issue due to it is pretty stale and seems there is a lack of demand - feel free to reopen or comment if this feature is really required.
