### ISSUE TITLE
Feat: Marshall protoPayload into JSON format

### ISSUE THREAD

**Issue by 0xSage** [googleapis/nodejs-logging#991]
Inspired by #785 and #984: 

Add `protoPayload` detection to [fromApiResponse](https://github.com/googleapis/nodejs-logging/blob/543533a02f293028081e7d31e3a98be1677b426a/src/entry.ts#L195) to automarshall proto into json format. Return an error or the original proto if marshalling fails. [Protobufjs](https://www.npmjs.com/package/protobufjs) library can be used. 

Such that when users call `getEntries` on audit logs that have protoPayloads, instead of text/JSON payloads, they get some structured payload information back. Some fields, nested fields, might still fail to marshal. 

Similar to [Go implementation](https://github.com/googleapis/google-cloud-go/blob/28decb55c366c5ec67e04800aa06179943b765f6/logging/logadmin/logadmin.go#L301).

This would be a breaking change.

**Comment by losalex** [comment]
Closing this issue due to it is pretty stale and seems there is a lack of demand - feel free to reopen or comment if this feature is really required.
